import { Pos, Spawner, Biome } from "./Structs.js";

const W_PLAINS = new Biome("Plains", ["plains", "river"], new Pos(4885, 67, -5538), new Pos(107, 0, 36), [
    new Spawner(new Pos(4936, 66, -5539), ["Ekans", "Oddish", "Mareep", "Rattata", "Sentret", "Spearow", "Zigzagoon", "Snubbull", "Voltorb", "Minun", "Plusle", "Gloom", "Flaaffy", "Miltank", "Raticate", "Skiploom", "Arbok", "Linoone", "Furret", "Electrode", "Vileplume", "Bellossom"]),
    new Spawner(new Pos(4968, 67, -5543), ["Miltank", "Ponyta", "Mareep", "Skiddo", "Wooloo", "Lechonk", "Tauros", "Bouffalant", "Mudbray", "Flaaffy", "Dubwool", "Oinkologne", "Rapidash", "Gogoat", "Mudsdale", "Ampharos"]),
    new Spawner(new Pos(4995, 67, -5531), ["Rattata", "Sentret", "Skitty", "Drifloon", "Litwick", "Meowth", "Seviper", "Zangoose", "Raticate", "Shuppet", "Drowzee", "Furret", "Persian", "Chingling", "Jigglypuff", "Scorbunny", "Chimecho", "Hypno", "Lampent", "Drifblim", "Zorua", "Zorua (Hisuian)", "Wigglytuff", "Zoroark"]),
    new Spawner(new Pos(5003, 67, -5484), ["Patrat", "Drowzee", "Purrloin", "Drifloon", "Espurr", "Shuppet", "Litwick", "Pumpkaboo", "Chingling", "Rattata (Alolan)", "Lampent", "Watchog", "Liepard", "Hypno", "Chimecho", "Drifblim", "Zorua (Hisuian)", "Gourgeist", "Raticate (Alolan)", "Zoroark (Hisuian)", "Umbreon"]),
    new Spawner(new Pos(5015, 67, -5470), ["Miltank", "Ponyta", "Mareep", "Skiddo", "Wooloo", "Lechonk", "Tauros", "Bouffalant", "Mudbray", "Flaaffy", "Dubwool", "Oinkologne", "Rapidash", "Gogoat", "Mudsdale", "Ampharos"]),
    new Spawner(new Pos(5044, 67, -5444), ["Pidove", "Cherubi", "Minccino", "Sentret", "Voltorb", "Meowth", "Sunkern", "Zangoose", "Furret", "Tranquill", "Cherrim", "Voltorb (Hisuian)", "Electrode", "Scorbunny", "Persian", "Seviper", "Raboot", "Sunflora", "Unfezant", "Electrode (Hisuian)", "Cinderace"]),
    new Spawner(new Pos(4976, 67, -5451), ["Electrike", "Ponyta", "Taillow", "Hoppip", "Pidgey", "Granbull", "Pidgeotto", "Jumpluff", "Electabuzz", "Farfetch'd", "Happiny", "Rapidash", "Ledyba", "Ledian", "Chespin", "Chikorita", "Bayleef", "Quilladin", "Manectric", "Pidgeot", "Meganium", "Chesnaught"]),
    new Spawner(new Pos(5031, 69, -5401), ["Wooloo", "Mareep", "Scatterbug", "Rattata", "Ekans", "Sewaddle", "Furfrou", "Farfetch'd", "Minun", "Plusle", "Electabuzz", "Flaaffy", "Bulbasaur", "Chikorita", "Raticate", "Farfetch'd (Galarian)", "Elekid", "Bayleef", "Vivillon", "Dubwool", "Sirfetch'd", "Electivire", "Espeon"]),
    new Spawner(new Pos(4919, 67, -5440), ["Zigzagoon", "Meowth", "Glameow", "Lillipup", "Patrat", "Furfrou", "Jigglypuff", "Tauros", "Linoone", "Bouffalant", "Herdier", "Meowth (Alolan)", "Persian", "Zigzagoon (Galarian)", "Bulbasaur", "Zorua", "Linoone (Galarian)", "Stoutland", "Purugly", "Ivysaur", "Venusaur", "Obstagoon", "Meganium"]),
    new Spawner(new Pos(4982, 66, -5383), ["Caterpie", "Weedle", "Pidove", "Cutiefly", "Combee", "Deerling", "Sunkern", "Sewaddle", "Flabebe", "Metapod", "Beedrill", "Floette", "Kakuna", "Swadloon", "Butterfree", "Ribombee", "Leavanny", "Pinsir", "Sunflora", "Sawsbuck", "Vespiquen", "Florges", "Sylveon"]),
    new Spawner(new Pos(5018, 68, -5353), ["Bounsweet", "Petilil", "Gossifleur", "Flabebe", "Combee", "Budew", "Comfey", "Cottonee", "Ledyba", "Roselia", "Steenee", "Floette", "Lilligant", "Whimsicott", "Vivillon", "Beautifly", "Bellossom", "Eldegoss", "Roserade", "Lilligant (Hisuian)", "Vespiquen", "Florges", "Tsareena"]),
    new Spawner(new Pos(4958, 68, -5319), ["Caterpie", "Weedle", "Pidove", "Cutiefly", "Combee", "Deerling", "Sunkern", "Sewaddle", "Flabebe", "Metapod", "Beedrill", "Floette", "Kakuna", "Swadloon", "Butterfree", "Ribombee", "Leavanny", "Pinsir", "Sunflora", "Sawsbuck", "Vespiquen", "Florges", "Sylveon"]),
    new Spawner(new Pos(4910, 67, -5343), ["Zigzagoon", "Meowth", "Glameow", "Lillipup", "Patrat", "Furfrou", "Jigglypuff", "Tauros", "Linoone", "Bouffalant", "Herdier", "Meowth (Alolan)", "Persian", "Zigzagoon (Galarian)", "Bulbasaur", "Zorua", "Linoone (Galarian)", "Stoutland", "Purugly", "Ivysaur", "Venusaur", "Obstagoon", "Meganium"]),
    new Spawner(new Pos(4924, 66, -5377), ["Bounsweet", "Petilil", "Gossifleur", "Flabebe", "Combee", "Budew", "Comfey", "Cottonee", "Ledyba", "Roselia", "Steenee", "Floette", "Lilligant", "Whimsicott", "Vivillon", "Beautifly", "Bellossom", "Eldegoss", "Roserade", "Lilligant (Hisuian)", "Vespiquen", "Florges", "Tsareena"]),
    new Spawner(new Pos(4868, 67, -5532), ["Miltank", "Ponyta", "Mareep", "Skiddo", "Wooloo", "Lechonk", "Tauros", "Bouffalant", "Mudbray", "Flaaffy", "Dubwool", "Oinkologne", "Rapidash", "Gogoat", "Mudsdale", "Ampharos"]),
    new Spawner(new Pos(4895, 67, -5560), ["Patrat", "Glameow", "Lillipup", "Ekans", "Lechonk", "Smoliv", "Jigglypuff", "Furret", "Zangoose", "Dolliv", "Herdier", "Seviper", "Arbok", "Oinkologne", "Watchog", "Stoutland", "Purugly", "Arboliva"]),
    new Spawner(new Pos(4889, 66, -5497), ["Electrike", "Ponyta", "Taillow", "Hoppip", "Pidgey", "Granbull", "Pidgeotto", "Jumpluff", "Electabuzz", "Farfetch'd", "Happiny", "Rapidash", "Ledyba", "Ledian", "Chespin", "Chikorita", "Bayleef", "Quilladin", "Manectric", "Pidgeot", "Meganium", "Chesnaught"]),
    new Spawner(new Pos(4866, 70, -5482), ["Rattata", "Sentret", "Skitty", "Drifloon", "Litwick", "Meowth", "Seviper", "Zangoose", "Raticate", "Shuppet", "Drowzee", "Furret", "Persian", "Chingling", "Jigglypuff", "Scorbunny", "Chimecho", "Hypno", "Lampent", "Drifblim", "Zorua", "Zorua (Hisuian)", "Wigglytuff", "Zoroark"]),
    new Spawner(new Pos(4846, 77, -5506), ["Ekans", "Oddish", "Mareep", "Rattata", "Sentret", "Spearow", "Zigzagoon", "Snubbull", "Voltorb", "Minun", "Plusle", "Gloom", "Flaaffy", "Miltank", "Raticate", "Skiploom", "Arbok", "Linoone", "Furret", "Electrode", "Vileplume", "Bellossom"]),
    new Spawner(new Pos(4851, 70, -5461), ["Fidough", "Maschiff", "Lillipup", "Snubbull", "Electrike", "Furfrou", "Herdier", "Zorua", "Granbull", "Zorua (Hisuian)", "Dachsbun", "Mabosstiff", "Zoroark", "Stoutland", "Zoroark (Hisuian)", "Manectric"]),
    new Spawner(new Pos(4879, 71, -5416), ["Pidove", "Cherubi", "Minccino", "Sentret", "Voltorb", "Meowth", "Sunkern", "Zangoose", "Furret", "Tranquill", "Cherrim", "Voltorb (Hisuian)", "Electrode", "Scorbunny", "Persian", "Seviper", "Raboot", "Sunflora", "Unfezant", "Electrode (Hisuian)", "Cinderace"]),
    new Spawner(new Pos(4854, 73, -5367), ["Wooloo", "Mareep", "Scatterbug", "Rattata", "Ekans", "Sewaddle", "Furfrou", "Farfetch'd", "Minun", "Plusle", "Electabuzz", "Flaaffy", "Bulbasaur", "Chikorita", "Raticate", "Farfetch'd (Galarian)", "Elekid", "Bayleef", "Vivillon", "Dubwool", "Sirfetch'd", "Electivire", "Espeon"]),
    new Spawner(new Pos(4820, 74, -5392), ["Patrat", "Drowzee", "Purrloin", "Drifloon", "Espurr", "Shuppet", "Litwick", "Pumpkaboo", "Chingling", "Rattata (Alolan)", "Lampent", "Watchog", "Liepard", "Hypno", "Chimecho", "Drifblim", "Zorua (Hisuian)", "Gourgeist", "Raticate (Alolan)", "Zoroark (Hisuian)", "Umbreon"]),
    // river biomes
    new Spawner(new Pos(4928, 66, -5484), ["Tympole", "Poliwag", "Goldeen", "Psyduck", "Tatsugiri", "Barboach", "Palpitoad", "Poliwhirl", "Golduck", "Seaking", "Dondozo", "Whiscash", "Poliwrath", "Crawdaunt", "Seismitoad", "Politoed"]),
    new Spawner(new Pos(4920, 66, -5475), ["Bidoof", "Magikarp", "Ducklett", "Surskit", "Carvanha", "Croagunk", "Tadbulb", "Pawniard", "Bibarel", "Buizel", "Bisharp", "Floatzel", "Masquerain", "Whiscash", "Araquanid", "Swanna", "Sobble", "Bellibolt", "Drizzile", "Inteleon"]),
    new Spawner(new Pos(4905, 66, -5466), ["Wooper", "Chewtle", "Basculin", "Ducklett", "Psyduck", "Marill", "Corphish", "Dewpider", "Buizel", "Totodile", "Quagsire", "Drednaw", "Croconaw", "Floatzel", "Golduck", "Azumarill", "Feraligatr", "Swanna", "Basculegion"]),
    new Spawner(new Pos(4895, 66, -5404), ["Bidoof", "Magikarp", "Ducklett", "Surskit", "Carvanha", "Croagunk", "Tadbulb", "Pawniard", "Bibarel", "Buizel", "Bisharp", "Floatzel", "Masquerain", "Whiscash", "Araquanid", "Swanna", "Sobble", "Bellibolt", "Drizzile", "Inteleon"]),
    new Spawner(new Pos(4883, 66, -5389), ["Wooper", "Chewtle", "Basculin", "Ducklett", "Psyduck", "Marill", "Corphish", "Dewpider", "Buizel", "Totodile", "Quagsire", "Drednaw", "Croconaw", "Floatzel", "Golduck", "Azumarill", "Feraligatr", "Swanna", "Basculegion"]),
    new Spawner(new Pos(4865, 66, -5337), ["Tympole", "Poliwag", "Goldeen", "Barboach", "Psyduck", "Palpitoad", "Poliwhirl", "Golduck", "Seaking", "Corphish", "Whiscash", "Poliwrath", "Quaxly", "Crawdaunt", "Seismitoad", "Quaxwell", "Politoed", "Quaquaval"])
]);

const W_BIRCHFOREST = new Biome("Birch Forest", ["birchforest"], new Pos(-5652, 74, 3470), new Pos(68, 0, 43), [
    new Spawner(new Pos(-5656, 71, 3499), ["Hoothoot", "Spinarak", "Murkrow", "Wurmple", "Ledian", "Abra", "Morpeko", "Cascoon", "Kadabra", "Noctowl", "Ariados", "Pikachu", "Falinks", "Dustox", "MrMime", "Teddiursa", "Ursaring", "MimeJr", "Raichu"]),
    new Spawner(new Pos(-5627, 73, 3496), ["Poochyena", "Minccino", "Stufful", "Ledyba", "Murkrow", "Nincada", "Milcery", "Pumpkaboo", "Phantump", "Spinarak", "Noibat", "Falinks", "Indeedee", "Applin", "Morpeko", "Eevee", "Furfrou", "Heracross", "Togetic", "Bulbasaur", "Turtwig", "Chespin", "Noivern", "Gallade"]),
    new Spawner(new Pos(-5603, 74, 3505), ["Minccino", "Stufful", "Oricorio", "Fletchling", "Teddiursa", "Timburr", "Plusle", "Gurdurr", "Ralts", "Turtwig", "Kirlia", "Fletchinder", "Grotle", "Conkeldurr", "Cinccino", "Torterra"]),
    new Spawner(new Pos(-5613, 74, 3574), ["Pidove", "Buneary", "Fletchling", "Scatterbug", "Timburr", "Tranquill", "Deerling", "Skiddo", "Dedenne", "Furfrou", "Minccino", "Spritzee", "Oricorio", "Spewpa", "Fletchinder", "Sawsbuck", "Vivillon", "Gogoat", "Unfezant", "Talonflame"]),
    new Spawner(new Pos(-5654, 73, 3565), ["Skwovet", "Espurr", "Kricketot", "Cherubi", "Taillow", "Plusle", "Minun", "Morelull", "Abra", "Greedent", "Swellow", "Falinks", "Indeedee", "Applin", "Chespin", "Bulbasaur", "Audino", "Ivysaur", "Venusaur", "Leafeon"]),
    new Spawner(new Pos(-5664, 74, 3616), ["Woobat", "Foongus", "Stunky", "Indeedee", "Phantump", "Pumpkaboo", "Bounsweet", "Amoonguss", "Skuntank", "Noibat", "Trevenant", "Noivern", "Tsareena"]),
    new Spawner(new Pos(-5577, 74, 3615), ["Weedle", "Wurmple", "Ledyba", "Ralts", "Nincada", "Kakuna", "Cascoon", "Silcoon", "Kirlia", "Beedrill", "Beautifly", "Dustox", "Stantler", "Ledian", "Ninjask", "Teddiursa", "Heracross", "Ursaring", "Gardevoir"]),
    new Spawner(new Pos(-5577, 73, 3666), ["Poochyena", "Minccino", "Stufful", "Ledyba", "Murkrow", "Nincada", "Milcery", "Pumpkaboo", "Phantump", "Spinarak", "Noibat", "Falinks", "Indeedee", "Applin", "Morpeko", "Eevee", "Furfrou", "Heracross", "Togetic", "Bulbasaur", "Turtwig", "Chespin", "Noivern", "Gallade"]),
    new Spawner(new Pos(-5564, 74, 3469), ["Woobat", "Foongus", "Stunky", "Indeedee", "Phantump", "Pumpkaboo", "Bounsweet", "Amoonguss", "Skuntank", "Noibat", "Trevenant", "Noivern", "Tsareena"]),
    new Spawner(new Pos(-5518, 74, 3503), ["Skwovet", "Espurr", "Kricketot", "Cherubi", "Taillow", "Plusle", "Minun", "Abra", "Greedent", "Swellow", "Falinks", "Indeedee", "Applin", "Chespin", "Bulbasaur", "Audino", "Ivysaur", "Venusaur", "Leafeon"]),
    new Spawner(new Pos(-5522, 72, 3550), ["Wurmple", "Ralts", "Teddiursa", "Pachirisu", "Abra", "Milcery", "Swablu", "Kirlia", "Silcoon", "Togetic", "Ursaring", "Beedrill", "Kadabra", "Oricorio", "Pikachu", "Stufful", "Applin", "Beautifly", "Eevee", "Turtwig", "Altaria", "Bewear", "Gardevoir", "Grotle", "Torterra"]),
    new Spawner(new Pos(-5509, 74, 3621), ["Wurmple", "Ralts", "Teddiursa", "Pachirisu", "Abra", "Milcery", "Swablu", "Kirlia", "Silcoon", "Togetic", "Ursaring", "Beedrill", "Kadabra", "Oricorio", "Pikachu", "Stufful", "Applin", "Beautifly", "Eevee", "Turtwig", "Altaria", "Bewear", "Gardevoir", "Grotle", "Torterra"]),
    new Spawner(new Pos(-5491, 74, 3615), ["Hoothoot", "Spinarak", "Murkrow", "Wurmple", "Ledian", "Abra", "Morpeko", "Cascoon", "Kadabra", "Noctowl", "Ariados", "Pikachu", "Falinks", "Dustox", "MrMime", "Teddiursa", "Ursaring", "MimeJr", "Raichu"]),
    new Spawner(new Pos(-5455, 81, 3526), ["Weedle", "Wurmple", "Ledyba", "Ralts", "Nincada", "Kakuna", "Cascoon", "Silcoon", "Kirlia", "Beedrill", "Beautifly", "Dustox", "Stantler", "Ledian", "Ninjask", "Teddiursa", "Heracross", "Ursaring", "Gardevoir"]),
    new Spawner(new Pos(-5635, 99, 3492), ["Pidove", "Buneary", "Fletchling", "Scatterbug", "Timburr", "Tranquill", "Deerling", "Skiddo", "Dedenne", "Furfrou", "Minccino", "Spritzee", "Oricorio", "Spewpa", "Fletchinder", "Sawsbuck", "Vivillon", "Gogoat", "Unfezant", "Talonflame"]),
    // river biomes
    new Spawner(new Pos(-5571, 72, 3497), ["Magikarp", "Goldeen", "Basculin", "Ducklett", "Poliwag", "Barboach", "Tympole", "Carvanha", "Seaking", "Whiscash", "Poliwrath"]),
    new Spawner(new Pos(-5559, 71, 3505), ["Bidoof", "Wooper", "Corphish", "Poliwag", "Buizel", "Marill", "Psyduck", "Chewtle", "Totodile", "Sobble", "Drednaw", "Azumarill"]),
    new Spawner(new Pos(-5571, 72, 3534), ["Magikarp", "Goldeen", "Basculin", "Ducklett", "Poliwag", "Barboach", "Tympole", "Carvanha", "Seaking", "Whiscash", "Poliwrath"]),
    new Spawner(new Pos(-5558, 72, 3554), ["Bidoof", "Wooper", "Corphish", "Poliwag", "Buizel", "Marill", "Psyduck", "Chewtle", "Totodile", "Sobble", "Drednaw", "Azumarill"])
]);

const W_DARKFOREST = new Biome("Dark Forest", ["darkforest"], new Pos(-23, 65, -1843), new Pos(142, 0, 143), [
    new Spawner(new Pos(-34, 64, -1860), ["Paras", "Shroomish", "Ledyba", "Parasect", "Phantump", "Breloom", "Burmy", "Ledian", "Stantler", "Illumise", "Volbeat", "Scatterbug", "Pancham", "Heracross", "Inkay", "Trevenant", "Spritzee", "Fletchling", "Fletchinder", "Espurr", "Pumpkaboo", "Noibat"]),
    new Spawner(new Pos(-4, 64, -1856), ["Rattata", "Caterpie", "Burmy", "Shroomish", "Nickit", "Impidimp", "Abra", "Inkay", "Metapod", "Wurmple", "Pancham", "Pikachu", "Chimecho", "Pangoro", "Butterfree", "Jigglypuff", "Thievul", "Bulbasaur", "Snivy", "Leafeon", "Malamar"]),
    new Spawner(new Pos(-16, 63, -1966), ["Oddish", "Pidgey", "Bellsprout", "Abra", "Espurr", "Togetic", "Pidgeotto", "Weepinbell", "Kadabra", "Gothorita", "Teddiursa", "Eevee", "Meowstic", "Chespin", "Quilladin", "Pidgeot", "Ursaring", "Chesnaught", "Gothitelle"]),
    new Spawner(new Pos(0, 63, -1947), ["Murkrow", "Weedle", "Gothita", "Stunky", "Phantump", "Litwick", "Skitty", "Foongus", "Kakuna", "Mimikyu", "Oricorio", "Zubat", "Mothim", "Misdreavus", "Beedrill", "Delcatty", "Eevee", "Chandelure", "Turtwig", "Grotle", "Torterra"]),
    new Spawner(new Pos(-53, 63, -1931), ["Hoothoot", "Paras", "Murkrow", "Ledyba", "Breloom", "Ledian", "Illumise", "Volbeat", "Misdreavus", "Kadabra", "Noctowl", "Ariados", "MimeJr", "Teddiursa", "Ursaring"]),
    new Spawner(new Pos(71, 66, -1850), ["Paras", "Shroomish", "Ledyba", "Parasect", "Impidimp", "Gloom", "Burmy", "Breloom", "Ledian", "Stantler", "Volbeat", "Illumise", "Teddiursa", "Heracross", "Ursaring", "Grimmsnarl"]),
    new Spawner(new Pos(30, 69, -1740), ["Hoothoot", "Spinarak", "Taillow", "Shroomish", "Abra", "Ledyba", "Sinistea", "Breloom", "Ledian", "Illumise", "Volbeat", "Swellow", "Misdreavus", "Kadabra", "Noctowl", "Ariados", "MimeJr", "Mismagius", "Mimikyu", "Polteageist"]),
    new Spawner(new Pos(-28, 67, -1786), ["Teddiursa", "Shroomish", "Impidimp", "Ledyba", "Parasect", "Cherubi", "Volbeat", "Breloom", "Burmy", "Ledian", "Stantler", "Illumise", "Morgrem", "Heracross", "Bulbasaur", "Ursaring", "Grimmsnarl", "Cherrim"]),
    new Spawner(new Pos(-55, 68, -1730), ["Oddish", "Pidgey", "Bellsprout", "Abra", "Pidgeotto", "Togetic", "Weepinbell", "Gloom", "Kadabra", "Skitty", "Eevee", "Mimikyu", "Chespin", "Bulbasaur", "Quilladin", "Ivysaur", "Pidgeot", "Vileplume", "Victreebel", "Chesnaught", "Venusaur"]),
    new Spawner(new Pos(-95, 66, -1761), ["Oddish", "Pidgey", "Bellsprout", "Abra", "Espurr", "Togetic", "Pidgeotto", "Weepinbell", "Kadabra", "Gothorita", "Teddiursa", "Eevee", "Meowstic", "Pidgeot", "Ursaring", "Chesnaught", "Gothitelle"]),
    new Spawner(new Pos(-106, 67, -1833), ["Paras", "Shroomish", "Ledyba", "Parasect", "Impidimp", "Gloom", "Burmy", "Breloom", "Ledian", "Stantler", "Volbeat", "Illumise", "Teddiursa", "Heracross", "Ursaring", "Grimmsnarl"]),
    new Spawner(new Pos(-72, 94, -1873), ["Teddiursa", "Shroomish", "Impidimp", "Ledyba", "Parasect", "Cherubi", "Volbeat", "Breloom", "Burmy", "Ledian", "Stantler", "Illumise", "Morgrem", "Heracross", "Bulbasaur", "Ursaring", "Grimmsnarl", "Cherrim"]),
    new Spawner(new Pos(-66, 114, -1898), ["Hoothoot", "Paras", "Murkrow", "Ledyba", "Breloom", "Ledian", "Illumise", "Volbeat", "Misdreavus", "Kadabra", "Noctowl", "Ariados", "MimeJr", "Teddiursa", "Ursaring", "Alakazam"]),
    new Spawner(new Pos(41, 88, -1808), ["Oddish", "Pidgey", "Bellsprout", "Abra", "Pidgeotto", "Togetic", "Weepinbell", "Gloom", "Kadabra", "Skitty", "Eevee", "Mimikyu", "Chespin", "Bulbasaur", "Quilladin", "Ivysaur", "Pidgeot", "Vileplume", "Victreebel", "Chesnaught", "Venusaur"]),
    new Spawner(new Pos(41, 83, -1766), ["Paras", "Shroomish", "Ledyba", "Parasect", "Phantump", "Breloom", "Burmy", "Ledian", "Stantler", "Illumise", "Volbeat", "Scatterbug", "Pancham", "Heracross", "Inkay", "Trevenant", "Spritzee", "Fletchling", "Fletchinder", "Espurr", "Pumpkaboo", "Noibat"]),
    new Spawner(new Pos(-48, 83, -1758), ["Hoothoot", "Spinarak", "Taillow", "Shroomish", "Abra", "Ledyba", "Sinistea", "Breloom", "Ledian", "Illumise", "Volbeat", "Swellow", "Misdreavus", "Kadabra", "Noctowl", "Ariados", "MimeJr", "Mismagius", "Mimikyu", "Polteageist"]),
    new Spawner(new Pos(-60, 101, -1801), ["Rattata", "Caterpie", "Burmy", "Shroomish", "Nickit", "Impidimp", "Abra", "Inkay", "Metapod", "Wurmple", "Pancham", "Pikachu", "Chimecho", "Pangoro", "Butterfree", "Jigglypuff", "Thievul", "Bulbasaur", "Snivy", "Leafeon", "Malamar", "Ditto"]),
    new Spawner(new Pos(-103, 111, -1785), ["Murkrow", "Weedle", "Gothita", "Stunky", "Phantump", "Litwick", "Skitty", "Foongus", "Kakuna", "Mimikyu", "Oricorio", "Zubat", "Mothim", "Misdreavus", "Beedrill", "Delcatty", "Eevee", "Chandelure", "Turtwig", "Grotle", "Spiritomb", "Torterra"]),
    new Spawner(new Pos(-88, 66, -1896), ["Gastly", "Shuppet", "Duskull", "Honedge", "Espurr", "Litwick", "Poochyena", "Doublade", "Woobat", "Haunter", "Dusclops", "Lampent", "Banette", "Rattata (Alolan)", "Morpeko", "Swoobat", "Rotom", "Chandelure", "Aegislash", "Gengar", "Dusknoir", "Spiritomb"], true),
    new Spawner(new Pos(-98, 67, -1795), ["Gastly", "Shuppet", "Duskull", "Honedge", "Espurr", "Litwick", "Poochyena", "Doublade", "Woobat", "Haunter", "Dusclops", "Lampent", "Banette", "Rattata (Alolan)", "Morpeko", "Swoobat", "Rotom", "Chandelure", "Aegislash", "Gengar", "Dusknoir", "Spiritomb"], true)
]);

const W_OCEAN = new Biome("Ocean", ["ocean"], new Pos(3219, 64, 1739), new Pos(285, 0, 143), [
    new Spawner(new Pos(3185, 63, 1761), ["Clamperl", "Slowpoke", "Crawdaunt", "Shellos", "Slowbro", "Clauncher", "Mareanie", "Shellder", "Squirtle", "Wartortle", "Blastoise", "Clawitzer", "Dragonite"]),
    new Spawner(new Pos(3129, 64, 1785), ["Wingull", "Corphish", "Marill", "Krabby", "Clamperl", "Clobbopus", "Pelipper", "Slowpoke", "Azumarill", "Kingler", "Azurill", "Slowbro", "Grapploct", "Oshawott", "Shellder", "Squirtle", "Blastoise", "Dewott", "Samurott", "Wartortle"]),
    new Spawner(new Pos(3102, 64, 1788), ["Magikarp", "Remoraid", "Tentacool", "Corphish", "Corsola", "Luvdisc", "Mantine", "Krabby", "Wailmer", "Clamperl", "Goldeen", "Horsea", "Staryu", "Tentacruel", "Carvanha", "Kingler", "Gorebyss", "Seadra", "Seaking", "Oshawott", "Chinchou", "Shellder", "Lapras", "Milotic", "Dewott", "Samurott", "Lanturn"]),
    new Spawner(new Pos(3112, 64, 1799), ["Wishiwashi", "Carvanha", "Wailmer", "Frillish", "Skrelp", "Tynamo", "Clawitzer", "Eelektrik", "Sharpedo", "Jellicent", "Dhelmise", "Eelektross", "Bruxish", "Mantine", "Gyarados", "Wailord", "Dragalge", "Lumineon"]),
    new Spawner(new Pos(3063, 64, 1847), ["Finneon", "Remoraid", "Wishiwashi", "Horsea", "Wailmer", "Mantine", "Mareanie", "Glimmet", "Seadra", "Gastrodon", "Gorebyss", "Huntail", "Lapras", "Lumineon", "Basculegion", "Glimmora", "Kingdra"]),
    new Spawner(new Pos(2997, 67, 1815), ["Clamperl", "Magikarp", "Shellder", "Finneon", "Tentacool", "Staryu", "Goldeen", "Horsea", "Seaking", "Alomomola", "Basculin", "Frillish", "Lumineon", "Seadra", "Tentacruel", "Jellicent", "Stunfisk", "Tynamo", "Chinchou", "Corsola", "Skrelp", "Lanturn", "Wailord", "Dragonair", "Dratini"]),
    new Spawner(new Pos(3018, 63, 1750), ["Chinchou", "Clamperl", "Goldeen", "Magikarp", "Staryu", "Qwilfish", "Tentacool", "Arrokuda", "Goldeen", "Frillish", "Carvanha", "Shellder", "Shellos", "Barraskewda", "Bruxish", "Lapras", "Starmie", "Dragonite", "Gyarados"]),
    new Spawner(new Pos(3045, 71, 1664), ["Finneon", "Remoraid", "Wishiwashi", "Horsea", "Wailmer", "Mantine", "Mareanie", "Glimmet", "Seadra", "Gastrodon", "Gorebyss", "Huntail", "Lapras", "Lumineon", "Basculegion", "Glimmora", "Kingdra"]),
    new Spawner(new Pos(3019, 67, 1637), ["Tentacool", "Magikarp", "Chinchou", "Qwilfish", "Clamperl", "Goldeen", "Staryu", "Tentacruel", "Octillery", "Carvanha", "Huntail", "Sharpedo", "Seaking", "Qwilfish (Hisuian)", "Crawdaunt", "Shellos", "Relicanth", "Corsola", "Shellder", "Corsola (Galarian)", "Dragonair", "Gyarados", "Basculegion", "Overqwil"]),
    new Spawner(new Pos(3064, 67, 1620), ["Wingull", "Corphish", "Marill", "Krabby", "Clamperl", "Clobbopus", "Pelipper", "Slowpoke", "Azumarill", "Kingler", "Azurill", "Slowbro", "Grapploct", "Oshawott", "Shellder", "Squirtle", "Blastoise", "Dewott", "Samurott", "Wartortle"]),
    new Spawner(new Pos(3100, 66, 1671), ["Clamperl", "Slowpoke", "Crawdaunt", "Shellos", "Slowbro", "Clauncher", "Mareanie", "Shellder", "Squirtle", "Wartortle", "Blastoise", "Clawitzer", "Dragonite"]),
    new Spawner(new Pos(3125, 66, 1687), ["Clamperl", "Magikarp", "Shellder", "Finneon", "Tentacool", "Staryu", "Goldeen", "Horsea", "Seaking", "Alomomola", "Basculin", "Frillish", "Lumineon", "Seadra", "Tentacruel", "Jellicent", "Stunfisk", "Tynamo", "Chinchou", "Corsola", "Skrelp", "Lanturn", "Wailord", "Dragonair", "Dratini"]),
    new Spawner(new Pos(3149, 66, 1697), ["Chinchou", "Qwilfish", "Arrokuda", "Clamperl", "Goldeen", "Staryu", "Tentacruel", "Octillery", "Carvanha", "Barraskewda", "Huntail", "Sharpedo", "Qwilfish (Hisuian)", "Seaking", "Crawdaunt", "Shellos", "Relicanth", "Corsola", "Shellder", "Dragonair", "Gyarados", "Overqwil"]),
    new Spawner(new Pos(3177, 56, 1711), ["Wishiwashi", "Carvanha", "Wailmer", "Frillish", "Veluza", "Skrelp", "Tynamo", "Clawitzer", "Eelektrik", "Sharpedo", "Jellicent", "Dhelmise", "Eelektross", "Bruxish", "Dratini", "Mantine", "Gyarados", "Wailord", "Dragalge", "Lumineon"]),
    new Spawner(new Pos(3157, 56, 1722), ["Horsea", "Finizen", "Skrelp", "Staryu", "Mareanie", "Seadra", "Toxapex", "Luvdisc", "Alomomola", "Mantine", "Palafin", "Lapras", "Glimmet", "Dragalge", "Starmie", "Kingdra"]),
    new Spawner(new Pos(3128, 27, 1734), ["Magikarp", "Remoraid", "Tentacool", "Corphish", "Corsola", "Luvdisc", "Mantine", "Krabby", "Wailmer", "Clamperl", "Goldeen", "Horsea", "Staryu", "Tentacruel", "Carvanha", "Kingler", "Gorebyss", "Seadra", "Seaking", "Oshawott", "Chinchou", "Shellder", "Lapras", "Milotic", "Dewott", "Samurott", "Lanturn", "Dhelmise"], true),
    new Spawner(new Pos(3101, 26, 1740), ["Tentacool", "Magikarp", "Chinchou", "Qwilfish", "Clamperl", "Goldeen", "Staryu", "Tentacruel", "Octillery", "Carvanha", "Huntail", "Sharpedo", "Seaking", "Qwilfish (Hisuian)", "Crawdaunt", "Shellos", "Relicanth", "Corsola", "Shellder", "Corsola (Galarian)", "Dragonair", "Gyarados", "Basculegion", "Overqwil"], true),
    new Spawner(new Pos(3079, 34, 1748), ["Chinchou", "Qwilfish", "Arrokuda", "Clamperl", "Goldeen", "Staryu", "Tentacruel", "Octillery", "Carvanha", "Barraskewda", "Huntail", "Sharpedo", "Qwilfish (Hisuian)", "Seaking", "Crawdaunt", "Shellos", "Relicanth", "Corsola", "Shellder", "Dragonair", "Gyarados", "Overqwil"], true),
    new Spawner(new Pos(3060, 30, 1736), ["Finneon", "Remoraid", "Wishiwashi", "Horsea", "Wailmer", "Mantine", "Mareanie", "Glimmet", "Seadra", "Gastrodon", "Gorebyss", "Huntail", "Lapras", "Lumineon", "Basculegion", "Glimmora", "Kingdra"], true),
    new Spawner(new Pos(3091, 34, 1702), ["Chinchou", "Clamperl", "Goldeen", "Magikarp", "Staryu", "Qwilfish", "Tentacool", "Arrokuda", "Goldeen", "Frillish", "Carvanha", "Shellder", "Shellos", "Barraskewda", "Bruxish", "Lapras", "Starmie", "Dragonite", "Gyarados"], true)
]);

const W_JUNGLE = new Biome("Jungle", ["jungle"], new Pos(-292, 80, 3233), new Pos(143, 0, 145), [
    new Spawner(new Pos(-364, 69, 3234), ["Venonat", "Venipede", "Natu", "Yanma", "Gloom", "Fomantis", "Tangela", "Venomoth", "Exeggcute", "Whirlipede", "Pinsir", "Scyther", "Joltik", "Aipom", "Lurantis", "Galvantula", "Scolipede", "Tangrowth"]),
    new Spawner(new Pos(-378, 68, 3214), ["Magikarp", "Basculin", "Goldeen", "Carvanha", "Tynamo"]),
    new Spawner(new Pos(-248, 68, 3191), ["Magikarp", "Basculin", "Goldeen", "Carvanha"]),
    new Spawner(new Pos(-344, 69, 3166), ["Tangela", "Pikipek", "Purrloin", "Bellsprout", "Oddish", "Exeggcute", "Aipom", "Carvanha", "Kecleon", "Pinsir", "Scyther", "Axew", "Treecko", "Grookey", "Noibat", "Litten", "Bellossom", "Vileplume", "Sceptile"]),
    new Spawner(new Pos(-283, 69, 3161), ["Venonat", "Venipede", "Natu", "Venomoth", "Exeggcute", "Whirlipede", "Pinsir", "Scyther", "Exeggutor", "Fraxure", "Joltik", "Galvantula", "Scolipede"]),
    new Spawner(new Pos(-257, 69, 3182), ["Slakoth", "Mankey", "Yanma", "Pikipek", "Panpour", "Chatot", "Joltik", "Treecko", "Tropius", "Paras", "Grookey", "Vigoroth", "Grovyle", "Thwackey", "Torracat", "Parasect", "Oranguru", "Slaking", "Rillaboom", "Lurantis"]),
    new Spawner(new Pos(-242, 68, 3169), ["Magikarp", "Basculin", "Goldeen", "Carvanha", "Sobble"]),
    new Spawner(new Pos(-230, 69, 3207), ["Yanma", "Oddish", "Grubbin", "Caterpie", "Metapod", "Tangela", "Slakoth", "Fomantis", "Vivillon", "Kecleon", "Butterfree", "Axew", "Lurantis", "Ambipom", "Noibat", "Litten", "Oranguru", "Slaking", "Exeggutor (Alolan)", "Haxorus"]),
    new Spawner(new Pos(-186, 69, 3233), ["Mankey", "Aipom", "Pansage", "Pansear", "Panpour", "Passimian", "Oranguru", "Simipour", "Simisage", "Simisear", "Grookey", "Primeape", "Thwackey", "Ambipom", "Rillaboom", "Annihilape"]),
    new Spawner(new Pos(-232, 69, 3265), ["Pancham", "Tangela", "Shroodle", "Venipede", "Natu", "Slakoth", "Joltik", "Whirlipede", "Grafaiai", "Kecleon", "Pinsir", "Xatu", "Litten", "Pangoro", "Scolipede", "Tangrowth"]),
    new Spawner(new Pos(-278, 69, 3317), ["Venonat", "Venipede", "Natu", "Venomoth", "Slakoth", "Whirlipede", "Fraxure", "Kecleon", "Pinsir", "Exeggutor", "Joltik", "Treecko", "Scolipede", "Slither Wing", "Kingambit"]),
    new Spawner(new Pos(-306, 68, 3299), ["Magikarp", "Basculin", "Goldeen", "Carvanha", "Barraskewda"]),
    new Spawner(new Pos(-322, 69, 3287), ["Venonat", "Venipede", "Natu", "Yanma", "Gloom", "Fomantis", "Venomoth", "Exeggcute", "Whirlipede", "Pinsir", "Scyther", "Joltik", "Passimian", "Komala", "Lurantis", "Galvantula", "Oranguru", "Scolipede", "Rillaboom"]),
    new Spawner(new Pos(-340, 69, 3289), ["Slakoth", "Mankey", "Fomantis", "Pikipek", "Pansage", "Chatot", "Joltik", "Treecko", "Emolga", "Paras", "Litten", "Vigoroth", "Grovyle", "Thwackey", "Torracat", "Primeape", "Passimian", "Slaking", "Incineroar", "Yanmega"]),
    new Spawner(new Pos(-374, 69, 3266), ["Pikipek", "Chatot", "Natu", "Emolga", "Xatu", "Trumbeak", "Yanma", "Tropius", "Toucannon", "Yanmega"]),
    new Spawner(new Pos(-289, 107, 3235), ["Pikipek", "Chatot", "Natu", "Emolga", "Xatu", "Trumbeak", "Yanma", "Tropius", "Toucannon", "Yanmega"]),
    new Spawner(new Pos(-310, 117, 3238), ["Hawlucha", "Carnivine", "Mankey", "Aipom", "Slakoth", "Passimian", "Pansage", "Pansear", "Panpour", "Oranguru", "Grookey"]),
    new Spawner(new Pos(-369, 109, 3143), ["Yanma", "Oddish", "Grubbin", "Caterpie", "Metapod", "Tangela", "Slakoth", "Fomantis", "Vivillon", "Kecleon", "Butterfree", "Axew", "Lurantis", "Ambipom", "Noibat", "Litten", "Oranguru", "Slaking", "Exeggutor (Alolan)", "Haxorus"]),
    new Spawner(new Pos(-215, 109, 3143), ["Tangela", "Pikipek", "Purrloin", "Bellsprout", "Oddish", "Exeggcute", "Aipom", "Carnivine", "Kecleon", "Pinsir", "Scyther", "Axew", "Treecko", "Grookey", "Noibat", "Litten", "Bellossom", "Vileplume", "Sceptile"]),
    new Spawner(new Pos(-176, 108, 3202), ["Pikipek", "Chatot", "Natu", "Emolga", "Xatu", "Trumbeak", "Yanma", "Tropius", "Toucannon", "Yanmega"]),
    new Spawner(new Pos(-219, 108, 3322), ["Venonat", "Venipede", "Natu", "Yanma", "Gloom", "Fomantis", "Venomoth", "Exeggcute", "Whirlipede", "Pinsir", "Scyther", "Joltik", "Passimian", "Komala", "Lurantis", "Galvantula", "Oranguru", "Scolipede", "Rillaboom"]),
    new Spawner(new Pos(-368, 109, 3323), ["Hawlucha", "Carnivine", "Mankey", "Aipom", "Slakoth", "Passimian", "Pansage", "Pansear", "Panpour", "Oranguru", "Grookey"])
]);

const W_DESERT = new Biome("Desert", ["desert"], new Pos(-1740, 69, -1160), new Pos(188, 0, 73), [
    new Spawner(new Pos(-1704, 70, -1142), ["Diglett", "Trapinch", "Numel", "Cyclizar", "Dugtrio", "Orthworm", "Magmar", "Vibrava", "Camerupt", "Fennekin", "Larvesta", "Braixen", "Flygon", "Delphox", "Dunsparce", "Dudunsparce"]),
    new Spawner(new Pos(-1688, 75, -1104), ["Diglett", "Geodude", "Hippopotas", "Trapinch", "Cubone", "Cacnea", "Helioptile", "Silicobra", "Magmar", "Vibrava", "Heliolisk", "Diglett (Alolan)", "Geodude (Alolan)", "Marowak", "Marowak (Alolan)", "Castform (Sun)", "Golem", "Golem (Alolan)", "Flygon"]),
    new Spawner(new Pos(-1703, 68, -1176), ["Vullaby", "Darumaka", "Maractus", "Sizzlipede", "Mandibuzz", "Heatmor", "Durant", "Hippopotas", "Drilbur", "Scraggy", "Yamask", "Druddigon", "Helioptile", "Hippowdon", "Cofagrigus", "Centiskorch", "Excadrill"]),
    new Spawner(new Pos(-1768, 67, -1164), ["Diglett", "Geodude", "Sandshrew", "Sandile", "Slugma", "Skorupi", "Houndour", "Cacnea", "Graveler", "Sandslash", "Dugtrio", "Magcargo", "Cubone", "Drapion", "Houndoom", "Silicobra", "Marowak", "Trapinch", "Numel", "Krokorok", "Dunsparce", "Krookodile", "Camerupt", "Vibrava", "Flygon"]),
    new Spawner(new Pos(-1781, 68, -1199), ["Durant", "Slugma", "Salandit", "Bramblin", "Drapion", "Yamask", "Orthworm", "Hippowdon", "Scrafty", "Stonjourner", "Cofagrigus", "Darmanitan", "Golem", "Salazzle", "Runerigus", "Brambleghast"]),
    new Spawner(new Pos(-1818, 77, -1197), ["Houndour", "Slugma", "Numel", "Vullaby", "Magcargo", "Houndoom", "Magmar", "Cacnea", "Darumaka", "Dunsparce", "Sizzlipede", "Larvesta", "Vibrava", "Gible", "Fennekin", "Darmanitan", "Camerupt", "Delphox", "Magmortar"]),
    new Spawner(new Pos(-1845, 101, -1158), ["Houndour", "Slugma", "Numel", "Vullaby", "Magcargo", "Houndoom", "Magmar", "Cacnea", "Darumaka", "Dunsparce", "Sizzlipede", "Larvesta", "Vibrava", "Gible", "Fennekin", "Darmanitan", "Camerupt", "Delphox", "Magmortar"]),
    new Spawner(new Pos(-1818, 72, -1145), ["Cubone", "Durant", "Salandit", "Yamask", "Drilbur", "Scraggy", "Baltoy", "Silicobra", "Trapinch", "Maractus", "Hippopotas", "Cacnea", "Tepig", "Sandaconda", "Larvesta", "Pignite", "Emboar", "Volcarona"]),
    new Spawner(new Pos(-1843, 66, -1100), ["Vullaby", "Darumaka", "Maractus", "Sizzlipede", "Mandibuzz", "Heatmor", "Durant", "Hippopotas", "Drilbur", "Scraggy", "Yamask", "Druddigon", "Helioptile", "Hippowdon", "Cofagrigus", "Centiskorch", "Excadrill"]),
    new Spawner(new Pos(-1849, 77, -1070), ["Geodude", "Skorupi", "Graveler", "Cyclizar", "Cubone", "Dunsparce", "Marowak", "Sigilyph", "Trapinch", "Numel", "Tepig", "Larvesta", "Pignite", "Emboar", "Vibrava", "Camerupt", "Flygon", "Dudunsparce"]),
    new Spawner(new Pos(-1806, 70, -1070), ["Flittle", "Capsakid", "Helioptile", "Bramblin", "Hippopotas", "Krokorok", "Cyclizar", "Espathra", "Numel", "Scovillain", "Braixen", "Heliolisk", "Stonjourner", "Dunsparce", "Crocalor", "Darmanitan", "Krookodile", "Dudunsparce"]),
    new Spawner(new Pos(-1785, 67, -1087), ["Diglett", "Geodude", "Hippopotas", "Trapinch", "Cubone", "Cacnea", "Helioptile", "Silicobra", "Magmar", "Vibrava", "Heliolisk", "Diglett (Alolan)", "Geodude (Alolan)", "Castform (Sun)", "Golem", "Golem (Alolan)", "Flygon"]),
    new Spawner(new Pos(-1757, 69, -1115), ["Darumaka", "Cacnea", "Sandile", "Hippopotas", "Maractus", "Torkoal", "Cacturne", "Magmar", "Gible", "Dunsparce", "Hippowdon", "Magby", "Fuecoco", "Gabite", "Crocalor", "Darmanitan", "Garchomp", "Skeledirge"]),
    new Spawner(new Pos(-1790, 57, -1045), ["Fennekin", "Helioptile", "Unown"], true),
    new Spawner(new Pos(-1748, 57, -1045), ["Fennekin", "Helioptile", "Unown"], true),
    new Spawner(new Pos(-1764, 56, -1070), ["Golett", "Yamask", "Sigilyph", "Diglett", "Sandile", "Golurk", "Stonjourner", "Yamask (Galarian)", "Cofagrigus", "Runerigus"], true),
    new Spawner(new Pos(-1774, 56, -1070), ["Golett", "Yamask", "Sigilyph", "Diglett", "Sandile", "Golurk", "Stonjourner", "Yamask (Galarian)", "Cofagrigus", "Runerigus"], true),
    new Spawner(new Pos(-1769, 56, -1073), ["Unown"], true),
    new Spawner(new Pos(-1769, 75, -1024), ["Cubone", "Durant", "Salandit", "Yamask", "Drilbur", "Scraggy", "Baltoy", "Silicobra", "Trapinch", "Maractus", "Hippopotas", "Cacnea", "Tepig", "Sandaconda", "Larvesta", "Pignite", "Emboar", "Volcarona"], true)
]);

const W_EXTREMEHILLS = new Biome("Extreme Hills", ["ehills", "extremehills"], new Pos(-3488, 87, -4696), new Pos(117, 0, 34), [
    new Spawner(new Pos(-3530, 81, -4695), ["Spinda", "Geodude", "Starly", "Klink", "Spoink", "Shuckle", "Tyrogue", "Klang", "Graveler", "Grumpig", "Clefairy", "Hitmontop", "Staravia", "Onix", "Castform", "Duraludon", "Klinklang", "Staraptor", "Lucario"]),
    new Spawner(new Pos(-3508, 86, -4677), ["Pidgey", "Spoink", "Machop", "Spearow", "Rufflet", "Starly", "Shuckle", "Tyrogue", "Torkoal", "Corvisquire", "Phanpy", "Fearow", "Pidgeotto", "Staravia", "Braviary", "Castform", "Donphan", "Grumpig", "Hitmonlee", "Machoke", "Onix", "Charmander", "Chimchar", "Pidgeot", "Staraptor", "Charmeleon", "Duraludon", "Monferno", "Snorlax", "Charizard", "Infernape", "Rookidee"]),
    new Spawner(new Pos(-3474, 87, -4675), ["Rufflet", "Phanpy", "Starly", "Spoink", "Pidgey", "Shuckle", "Tyrogue", "Machop", "Jangmo-o", "Pidgeotto", "Onix", "Braviary", "Staravia", "Castform", "Hakamo-o", "Donphan", "Machoke", "Carbink", "Grumpig", "Charmander", "Chimchar", "Charmeleon", "Kommo-o", "Monferno", "Pidgeotto", "Staraptor", "Charizard", "Infernape"]), // duplicate: Pidgeotto
    new Spawner(new Pos(-3445, 87, -4658), ["Tyrogue", "Starly", "Rockruff", "Geodude", "Shuckle", "Togedemaru", "Spinda", "Graveler", "Carbink", "Hitmonchan", "Hitmonlee", "Hitmontop", "Clefairy", "Staravia", "Castform", "Lycanroc", "Onix", "Snorlax", "Staraptor", "Clefable"]),
    new Spawner(new Pos(-3416, 86, -4692), ["Whismur", "Makuhita", "Pawniard", "Mudbray", "Mienfoo", "Absol", "Skarmory", "Larvitar", "Hawlucha", "Druddigon", "Aron", "Torkoal", "Deino", "Gible", "Jangmo-o", "Noibat", "Bisharp", "Tyranitar", "Braviary (Hisuian)", "Nosepass", "Probopass"]),
    new Spawner(new Pos(-3383, 85, -4657), ["Mudbray", "Rolycoly", "Rockruff", "Togedemaru", "Mienfoo", "Timburr", "Woobat", "Durant", "Heatmor", "Gible", "Carkol", "Gurdurr", "Mienshao", "Deino", "Jangmo-o", "Sawk", "Throh", "Drampa", "Hakamo-o", "Hawlucha", "Kommo-o", "Mudsdale", "Turtonator", "Gabite", "Spiritomb", "Zweilous", "Lycanroc", "Carbink", "Garchomp", "Coalossal", "Hydreigon"]),
    new Spawner(new Pos(-3342, 81, -4627), ["Pidgey", "Phanpy", "Starly", "Geodude", "Shuckle", "Spoink", "Rufflet", "Graveler", "Machop", "Pidgeotto", "Castform", "Onix", "Donphan", "Grumpig", "Machoke", "Staravia", "Braviary", "Charmander", "Chimchar", "Charmeleon", "Monferno", "Pidgeot", "Snorlax", "Staraptor", "Hitmonlee", "Charizard", "Infernape"]),
    new Spawner(new Pos(-3545, 82, -4616), ["Rufflet", "Phanpy", "Starly", "Spoink", "Pidgey", "Shuckle", "Tyrogue", "Machop", "Jangmo-o", "Pidgeotto", "Onix", "Braviary", "Staravia", "Castform", "Hakamo-o", "Donphan", "Machoke", "Carbink", "Grumpig", "Snorlax", "Charmander", "Chimchar", "Charmeleon", "Kommo-o", "Monferno", "Pidgeotto", "Staraptor", "Charizard", "Infernape"]),
    new Spawner(new Pos(-3530, 82, -4517), ["Geodude", "Spinda", "Starly", "Shuppet", "Shuckle", "Elgyem", "Tyrogue", "Graveler", "Beheeyem", "Clefairy", "Hitmonchan", "Hitmontop", "Staravia", "Banette", "Castform", "Onix", "Druddigon", "Snorlax", "Clefable", "Staraptor"]),
    new Spawner(new Pos(-3543, 81, -4494), ["Mudbray", "Rolycoly", "Rockruff", "Togedemaru", "Mienfoo", "Timburr", "Woobat", "Durant", "Heatmor", "Gible", "Carkol", "Gurdurr", "Mienshao", "Deino", "Jangmo-o", "Sawk", "Throh", "Drampa", "Hakamo-o", "Hawlucha", "Kommo-o", "Mudsdale", "Turtonator", "Gabite", "Spiritomb", "Zweilous", "Lycanroc", "Carbink", "Garchomp", "Coalossal", "Hydreigon"]),
    new Spawner(new Pos(-3477, 87, -4554), ["Minior", "Rookidee", "Geodude", "Tyrogue", "Whismur", "Corvisquire", "Larvitar", "Pawniard", "Bisharp", "Graveler", "Loudred", "Makuhita", "Absol", "Meditite", "Lunatone", "Solrock", "Exploud", "Hariyama", "Pupitar", "Clefairy", "Sableye", "Skarmory", "Mawile", "Medicham", "Snorlax", "Castform", "Duraludon", "Hitmonchan", "Onix", "Clefable", "Tyranitar", "Carbink", "Corviknight"]),
    new Spawner(new Pos(-3446, 89, -4541), ["Pidgey", "Spoink", "Machop", "Spearow", "Rufflet", "Starly", "Shuckle", "Tyrogue", "Torkoal", "Corvisquire", "Phanpy", "Fearow", "Pidgeotto", "Staravia", "Braviary", "Castform", "Donphan", "Grumpig", "Hitmonlee", "Machoke", "Onix", "Charmander", "Chimchar", "Pidgeot", "Staraptor", "Charmeleon", "Duraludon", "Monferno", "Snorlax", "Charizard", "Infernape", "Rookidee"]),
    new Spawner(new Pos(-3418, 87, -4490), ["Spinda", "Geodude", "Starly", "Klink", "Spoink", "Shuckle", "Tyrogue", "Klang", "Graveler", "Grumpig", "Clefairy", "Hitmontop", "Staravia", "Onix", "Castform", "Duraludon", "Klinklang", "Staraptor", "Lucario"]),
    new Spawner(new Pos(-3473, 82, -4474), ["Rolycoly", "Roggenrola", "Timburr", "Mienfoo", "Woobat", "Durant", "Heatmor", "Carkol", "Sawk", "Throh", "Boldore", "Gible", "Gurdurr", "Deino", "Mienshao", "Coalossal", "Zweilous", "Gabite", "Spiritomb", "Garchomp", "Hydreigon"]),
    new Spawner(new Pos(-3485, 88, -4653), ["Geodude", "Zubat", "Whismur", "Shuckle", "Graveler", "Golbat", "Loudred", "Sableye", "Clefairy", "Mawile", "Druddigon", "Exploud", "Larvitar", "Clefable", "Pupitar", "Tyranitar", "Bisharp", "Turtonator", "Drampa"], true),
    new Spawner(new Pos(-3437, 79, -4641), ["Machop", "Rolycoly", "Pawniard", "Torkoal", "Elgyem", "Minior", "Solrock", "Timburr", "Riolu", "Chimchar", "Coalossal", "Absol", "Gible", "Turtonator", "Lucario", "Machamp"], true),
    new Spawner(new Pos(-3444, 79, -4625), ["Roggenrola", "Gastly", "Shuckle", "Larvitar", "Dunsparce", "Boldore", "Diglett", "Haunter", "Pupitar", "Clefairy", "Sableye", "Mawile", "Lunatone", "Solrock", "Dugtrio", "Tyranitar", "Steelix"], true),
    new Spawner(new Pos(-3472, 87, -4624), ["Bunnelby", "Geodude", "Drilbur", "Durant", "Larvitar", "Aron", "Diglett", "Graveler", "Diggersby", "Pupitar", "Clefairy", "Lairon", "Mawile", "Excadrill", "Carbink", "Dugtrio", "Duraludon", "Garchomp", "Aggron"], true),
    new Spawner(new Pos(-3439, 87, -4605), ["Geodude", "Shuckle", "Clefairy", "Larvitar", "Graveler", "Geodude (Alolan)", "Sableye", "Mawile", "Clefable", "Golem (Alolan)", "Nosepass", "Iron Thorns"], true),
    new Spawner(new Pos(-3430, 98, -4629), ["Diglett", "Whismur", "Shuckle", "Larvitar", "Onix", "Dugtrio", "Geodude", "Loudred", "Pupitar", "Clefairy", "Mawile", "Sableye", "Beldum", "Exploud", "Graveler", "Metang", "Metagross"], true)
]);

const W_BEACH = new Biome("Beach", ["beach", "stonebeach"], new Pos(3709, 74, 2812), new Pos(143, 0, 143), [
    new Spawner(new Pos(3673, 69, 2818), ["Corphish", "Krabby", "Marill", "Pelipper", "Wingull", "Slowpoke", "Azumarill", "Crabrawler", "Sandygast", "Kingler", "Azurill", "Slowbro", "Palossand", "Oshawott", "Popplio", "Shellder", "Squirtle", "Blastoise", "Brionne", "Dewott", "Primarina", "Samurott", "Wartortle"]),
    new Spawner(new Pos(3723, 69, 2842), ["Krabby", "Pyukumuku", "Binacle", "Clauncher", "Crabrawler", "Marill", "Sandygast", "Inkay", "Slowpoke", "Azumarill", "Pincurchin", "Wimpod", "Barbaracle", "Vaporeon", "Golisopod", "Slowbro", "Malamar"]),
    new Spawner(new Pos(3736, 69, 2809), ["Krabby", "Pyukumuku", "Shellder", "Binacle", "Slowpoke", "Squirtle", "Wartortle", "Wimpod", "Blastoise", "Golisopod"]),
    new Spawner(new Pos(3692, 69, 2789), ["Corphish", "Krabby", "Marill", "Pelipper", "Wingull", "Slowpoke", "Azumarill", "Crabrawler", "Sandygast", "Kingler", "Azurill", "Slowbro", "Palossand", "Oshawott", "Popplio", "Shellder", "Squirtle", "Blastoise", "Brionne", "Dewott", "Primarina", "Samurott", "Wartortle"]),
    new Spawner(new Pos(3738, 68, 2701), ["Dwebble", "Shelmet", "Slowpoke", "Crabrawler", "Crawdaunt", "Slowbro", "Slowpoke (Galarian)", "Pincurchin", "Shellder", "Squirtle", "Totodile", "Binacle", "Wartortle", "Croconaw", "Feraligatr", "Blastoise", "Slowbro (Galarian)"]),
    new Spawner(new Pos(3696, 68, 2714), ["Tentacool", "Magikarp", "Remoraid", "Corphish", "Corsola", "Krabby", "Horsea", "Staryu", "Corsola (Galarian)", "Kingler", "Seadra", "Seaking", "Qwilfish", "Qwilfish (Hisuian)", "Lumineon", "Shellder", "Cursola", "Samurott"]),
    new Spawner(new Pos(3686, 68, 2747), ["Dwebble", "Shelmet", "Slowpoke", "Crabrawler", "Crawdaunt", "Slowbro", "Slowpoke (Galarian)", "Pincurchin", "Shellder", "Squirtle", "Totodile", "Binacle", "Wartortle", "Croconaw", "Feraligatr", "Blastoise", "Slowbro (Galarian)"]),
    new Spawner(new Pos(3651, 68, 2761), ["Tentacool", "Magikarp", "Remoraid", "Corphish", "Corsola", "Krabby", "Horsea", "Staryu", "Finneon", "Goldeen", "Corsola (Galarian)", "Kingler", "Seadra", "Seaking", "Qwilfish", "Qwilfish (Hisuian)", "Lumineon", "Shellder", "Cursola", "Samurott"]),
    new Spawner(new Pos(3635, 68, 2804), ["Dwebble", "Shelmet", "Slowpoke", "Crabrawler", "Crawdaunt", "Slowbro", "Slowpoke (Galarian)", "Shellder", "Cloyster", "Squirtle", "Totodile", "Binacle", "Wartortle", "Croconaw", "Feraligatr", "Blastoise", "Slowking", "Slowking (Galarian)"]),
    new Spawner(new Pos(3615, 68, 2799), ["Tentacool", "Magikarp", "Remoraid", "Corphish", "Corsola", "Krabby", "Horsea", "Staryu", "Finneon", "Goldeen", "Corsola (Galarian)", "Kingler", "Seadra", "Seaking", "Qwilfish", "Qwilfish (Hisuian)", "Lumineon", "Shellder", "Cursola", "Samurott"]),
    new Spawner(new Pos(3591, 68, 2876), ["Corphish", "Krabby", "Marill", "Pelipper", "Wingull", "Slowpoke", "Azumarill", "Crabrawler", "Sandygast", "Kingler", "Azurill", "Wimpod", "Slowbro", "Palossand", "Oshawott", "Popplio", "Brionne", "Dewott", "Primarina", "Samurott"]),
    // stone beach
    new Spawner(new Pos(3682, 97, 2916), ["Pyukumuku", "Binacle", "Clauncher", "Dwebble", "Marill", "Shuckle", "Azumarill", "Crustle", "Barbaracle", "Golisopod", "Cramorant", "Raichu (Alolan)"]),
    new Spawner(new Pos(3689, 97, 2888), ["Finneon", "Magikarp", "Krabby", "Clauncher", "Inkay", "Staryu", "Oshawott", "Dewott", "Samurott", "Malamar"]),
    new Spawner(new Pos(3739, 107, 2887), ["Pyukumuku", "Nacli", "Binacle", "Clauncher", "Dwebble", "Marill", "Shuckle", "Naclstack", "Azumarill", "Crustle", "Barbaracle", "Golisopod", "Garganacl"]),
    new Spawner(new Pos(3775, 111, 2861), ["Krabby", "Pyukumuku", "Dwebble", "Marill", "Shellder", "Cramorant", "Wimpod", "Kingler", "Sandygast", "Kingler", "Slowbro", "Golisopod", "Raichu (Alolan)"]), // duplicate: Kingler
    new Spawner(new Pos(3776, 110, 2821), ["Pyukumuku", "Nacli", "Binacle", "Clauncher", "Dwebble", "Marill", "Shuckle", "Naclstack", "Azumarill", "Crustle", "Barbaracle", "Golisopod", "Garganacl"]),
    new Spawner(new Pos(3804, 110, 3852), ["Finneon", "Magikarp", "Krabby", "Clauncher", "Inkay", "Staryu", "Oshawott", "Dewott", "Samurott", "Malamar"]),
    new Spawner(new Pos(3810, 112, 2835), ["Krabby", "Pyukumuku", "Dwebble", "Shuckle", "Marill", "Shellder", "Cramorant", "Wimpod", "Cloyster", "Golisopod", "Kingler", "Slowking", "Raichu (Alolan)"]),
    new Spawner(new Pos(3797, 104, 2770), ["Wingull", "Pyukumuku", "Dwebble", "Pelipper", "Vivillon", "Shuckle", "Pincurchin", "Shellder", "Cramorant", "Comfey", "Exeggutor (Alolan)", "Dugtrio (Alolan)", "Golisopod", "Kingler", "Crustle"])
]);

const W_SAVANNA = new Biome("Savanna", ["savanna"], new Pos(7699, 65, 1073), new Pos(144, 0, 144), [
    new Spawner(new Pos(7696, 65, 1047), ["Ekans", "Growlithe", "Vulpix", "Arbok", "Scyther", "Purrloin", "Shinx", "Watchog", "Zebstrika", "Liepard", "Luxio", "Blitzle", "Patrat", "Lickitung", "Nidoking", "Nidoqueen", "Torchic", "Ninetales", "Bouffalant", "Litleo", "Luxray", "Audino", "Pyroar"]),
    new Spawner(new Pos(7708, 65, 1008), ["Nymble", "Starly", "Bramblin", "Flittle", "Tauros (Combat)", "Tauros", "Electrike", "Staravia", "Lokix", "Smoliv", "Espathra", "Bouffalant", "Skarmory", "Kangaskhan", "Staraptor", "Lickitung", "Brambleghast"]),
    new Spawner(new Pos(7707, 62, 956), ["Purrloin", "Patrat", "Blitzle", "Growlithe", "Cufant", "Litleo", "Rhyhorn", "Girafarig", "Komala", "Yamper", "Liepard", "Zebstrika", "Watchog", "Bouffalant", "Voltorb (Hisuian)", "Dreepy", "Drakloak", "Chansey", "Audino", "Pyroar", "Dragapult", "Blissey"]),
    new Spawner(new Pos(7813, 65, 1059), ["Ekans", "Nidoranfemale", "Nidoranmale", "Shinx", "Nidorina", "Nidorino", "Arbok", "Doduo", "Luxio", "Dodrio", "Tauros", "Kangaskhan", "Lickitung", "Scyther", "Happiny", "Vulpix", "Cyndaquil", "Torchic", "Combusken", "Blaziken", "Chansey", "Ditto", "Luxray", "Nidoqueen", "Quilava", "Typhlosion", "Nidoking", "Ninetales"]),
    new Spawner(new Pos(7794, 65, 1083), ["Ekans", "Growlithe", "Vulpix", "Arbok", "Scyther", "Purrloin", "Shinx", "Watchog", "Zebstrika", "Liepard", "Luxio", "Blitzle", "Patrat", "Lickitung", "Nidoking", "Nidoqueen", "Torchic", "Ninetales", "Bouffalant", "Litleo", "Luxray", "Audino", "Pyroar"]),
    new Spawner(new Pos(7725, 65, 1070), ["Patrat", "Honedge", "Cufant", "Yamper", "Ponyta", "Shinx", "Doublade", "Falinks", "Bouffalant", "Luxio", "Slugma", "Skarmory", "Tepig", "Torkoal", "Pignite", "Dreepy", "Aegislash", "Copperajah", "Jolteon", "Emboar", "Luxray", "Magcargo"]),
    new Spawner(new Pos(7750, 64, 1123), ["Electrike", "Growlithe", "Shinx", "Woobat", "Geodude", "Aron", "Sandshrew", "Blitzle", "Ekans", "Arbok", "Silicobra", "Dunsparce", "Onix", "Growlithe (Hisuian)", "Sandslash", "Carbink", "Solrock", "Bronzong", "Lunatone", "Arcanine (Hisuian)", "Arcanine", "Steelix"]),
    new Spawner(new Pos(7823, 63, 1122), ["Purrloin", "Patrat", "Blitzle", "Growlithe", "Cufant", "Litleo", "Rhyhorn", "Girafarig", "Komala", "Yamper", "Liepard", "Zebstrika", "Watchog", "Bouffalant", "Voltorb (Hisuian)", "Dreepy", "Drakloak", "Chansey", "Audino", "Pyroar", "Dragapult", "Rhyperior"]),
    new Spawner(new Pos(7714, 63, 1185), ["Electrike", "Growlithe", "Shinx", "Komala", "Honedge", "Girafarig", "Ponyta", "Cufant", "Lickitung", "Vullaby", "Falinks", "Doublade", "Yamper", "Tepig", "Dreepy", "Growlithe (Hisuian)", "Cyndaquil", "Skarmory", "Copperajah", "Jolteon", "Lickilicky"]),
    new Spawner(new Pos(7705, 62, 1114), ["Purrloin", "Patrat", "Blitzle", "Growlithe", "Cufant", "Litleo", "Rhyhorn", "Girafarig", "Komala", "Yamper", "Liepard", "Zebstrika", "Watchog", "Bouffalant", "Voltorb (Hisuian)", "Dreepy", "Drakloak", "Chansey", "Audino", "Pyroar", "Dragapult", "Blissey"]),
    new Spawner(new Pos(7671, 62, 1092), ["Smoliv", "Tauros (Combat)", "Yamper", "Litleo", "Cufant", "Electrike", "Blitzle", "Dolliv", "Girafarig", "Cyclizar", "Skarmory", "Manectric", "Pyroar", "Boltund", "Tauros (Blaze)", "Tauros (Aqua)", "Farigiraf", "Arboliva"]),
    new Spawner(new Pos(7660, 64, 1063), ["Ekans", "Nidoranfemale", "Nidoranmale", "Shinx", "Nidorina", "Nidorino", "Arbok", "Doduo", "Luxio", "Dodrio", "Tauros", "Kangaskhan", "Lickitung", "Scyther", "Happiny", "Vulpix", "Cyndaquil", "Torchic", "Combusken", "Blaziken", "Chansey", "Luxray", "Nidoqueen", "Quilava", "Typhlosion", "Nidoking", "Ninetales"]),
    new Spawner(new Pos(7609, 62, 1086), ["Electrike", "Growlithe", "Shinx", "Komala", "Honedge", "Girafarig", "Ponyta", "Cufant", "Lickitung", "Vullaby", "Falinks", "Doublade", "Yamper", "Tepig", "Dreepy", "Growlithe (Hisuian)", "Cyndaquil", "Skarmory", "Copperajah", "Jolteon", "Lickilicky", "Ditto"]),
    new Spawner(new Pos(7570, 61, 1088), ["Smoliv", "Tauros (Combat)", "Yamper", "Litleo", "Cufant", "Electrike", "Blitzle", "Dolliv", "Girafarig", "Cyclizar", "Skarmory", "Manectric", "Pyroar", "Boltund", "Tauros (Blaze)", "Tauros (Aqua)", "Farigiraf", "Arboliva"]),
    new Spawner(new Pos(7615, 63, 979), ["Patrat", "Honedge", "Cufant", "Yamper", "Ponyta", "Shinx", "Doublade", "Falinks", "Bouffalant", "Luxio", "Slugma", "Skarmory", "Tepig", "Torkoal", "Pignite", "Dreepy", "Aegislash", "Copperajah", "Jolteon", "Emboar", "Luxray", "Magcargo"]),
    new Spawner(new Pos(7624, 63, 979), ["Electrike", "Growlithe", "Shinx", "Woobat", "Geodude", "Aron", "Sandshrew", "Blitzle", "Ekans", "Arbok", "Silicobra", "Dunsparce", "Onix", "Growlithe (Hisuian)", "Sandslash", "Bronzong", "Lunatone", "Arcanine (Hisuian)", "Arcanine", "Steelix"]),
    new Spawner(new Pos(7638, 63, 1040), ["Starly", "Honedge", "Geodude", "Drilbur", "Whismur", "Bunnelby", "Zubat", "Onix", "Staravia", "Golbat", "Slugma", "Geodude (Alolan)", "Nosepass", "Torkoal", "Diggersby", "Dreepy", "Staraptor", "Magcargo", "Excadrill", "Steelix", "Probopass"], true),
    new Spawner(new Pos(7737, 65, 1036), ["Starly", "Honedge", "Geodude", "Drilbur", "Whismur", "Bunnelby", "Zubat", "Onix", "Staravia", "Golbat", "Slugma", "Geodude (Alolan)", "Nosepass", "Torkoal", "Diggersby", "Dreepy", "Staraptor", "Magcargo", "Excadrill", "Steelix", "Probopass"], true)
]);

const W_TAIGA = new Biome("Taiga", ["taiga"], new Pos(653, 72, 1616), new Pos(143, 0, 145), [
    new Spawner(new Pos(659, 72, 1588), ["Blipbug", "Pachirisu", "Nickit", "Stantler", "Dedenne", "Poochyena", "Greedent", "Teddiursa", "Dottler", "Exeggcute", "Heracross", "Pinsir", "Applin", "Pikachu", "Thievul", "Klefki", "Mightyena", "Snorlax", "Orbeetle", "Ursaring"]),
    new Spawner(new Pos(692, 71, 1602), ["Poochyena", "Seedot", "Heracross", "Pineco", "Morelull", "Exeggcute", "Deerling", "Togedemaru", "Dedenne", "Nuzleaf", "Hattrem", "Sawsbuck", "Forretress", "Teddiursa", "Shiinotic", "Mightyena", "Snorlax", "Ursaring"]),
    new Spawner(new Pos(659, 71, 1492), ["Pidgey", "Drowzee", "Murkrow", "Wurmple", "Nickit", "Hatenna", "Pikachu", "Yungoos", "Heracross", "Pidgeotto", "Oricorio", "Togetic", "Togedemaru", "Klefki", "Chespin", "Hypno", "Vikavolt", "Leafeon", "Hatterene", "Kleavor"]),
    new Spawner(new Pos(774, 71, 1663), ["Poochyena", "Seedot", "Heracross", "Pineco", "Morelull", "Exeggcute", "Deerling", "Togedemaru", "Dedenne", "Nuzleaf", "Hattrem", "Sawsbuck", "Forretress", "Teddiursa", "Shiinotic", "Mightyena", "Snorlax", "Ursaring"]),
    new Spawner(new Pos(586, 72, 1691), ["Pidgey", "Drowzee", "Murkrow", "Wurmple", "Nickit", "Hatenna", "Pikachu", "Yungoos", "Heracross", "Pidgeotto", "Oricorio", "Togetic", "Togedemaru", "Klefki", "Chespin", "Hypno", "Vikavolt", "Leafeon", "Hatterene", "Kleavor"]),
    new Spawner(new Pos(533, 71, 1666), ["Nincada", "Teddiursa", "Blipbug", "Grubbin", "Chingling", "Abra", "Stantler", "Exeggcute", "Ninjask", "Seedot", "Hatenna", "Nickit", "Mienfoo", "Murkrow", "Forretress", "MrMime", "Raichu", "Snorlax", "Mienshao", "Honchkrow", "Togekiss"]),
    new Spawner(new Pos(565, 72, 1640), ["Pawmi", "Seedot", "Hatenna", "Yungoos", "Rockruff", "Nuzleaf", "Pawmo", "Hattrem", "Pikachu", "Abra", "Klefki", "Gumshoos", "Shiftry", "Hatterene", "Pawmot", "Lycanroc"]),
    new Spawner(new Pos(615, 73, 1626), ["Pineco", "Grubbin", "Gastly", "Skwovet", "Abra", "Hoothoot", "Spinarak", "Teddiursa", "Mienfoo", "Poochyena", "Charjabug", "Greedent", "Thievul", "Chimecho", "Chingling", "Forretress", "Haunter", "Ariados", "Kadabra", "Mightyena", "Pikachu", "Noctowl", "MimeJr", "MrMime", "Mienshao", "Raichu", "Snorlax", "Ursaring"]),
    new Spawner(new Pos(635, 95, 1523), ["Pineco", "Grubbin", "Gastly", "Skwovet", "Abra", "Hoothoot", "Spinarak", "Teddiursa", "Mienfoo", "Poochyena", "Charjabug", "Greedent", "Thievul", "Chimecho", "Chingling", "Forretress", "Haunter", "Ariados", "Kadabra", "Mightyena", "Pikachu", "Noctowl", "MimeJr", "MrMime", "Mienshao", "Raichu", "Snorlax", "Ursaring"]),
    new Spawner(new Pos(615, 112, 1558), ["Pineco", "Grubbin", "Gastly", "Skwovet", "Abra", "Hoothoot", "Spinarak", "Teddiursa", "Mienfoo", "Poochyena", "Charjabug", "Greedent", "Thievul", "Chimecho", "Chingling", "Forretress", "Haunter", "Ariados", "Kadabra", "Mightyena", "Pikachu", "Noctowl", "MimeJr", "MrMime", "Mienshao", "Raichu", "Snorlax", "Ursaring"]),
    new Spawner(new Pos(684, 115, 1675), ["Blipbug", "Pachirisu", "Nickit", "Stantler", "Dedenne", "Poochyena", "Greedent", "Teddiursa", "Dottler", "Exeggcute", "Heracross", "Pinsir", "Applin", "Pikachu", "Thievul", "Klefki", "Mightyena", "Snorlax", "Orbeetle", "Ursaring"]),
    new Spawner(new Pos(721, 111, 1555), ["Pidgey", "Drowzee", "Murkrow", "Wurmple", "Nickit", "Hatenna", "Pikachu", "Yungoos", "Heracross", "Pidgeotto", "Oricorio", "Togetic", "Togedemaru", "Klefki", "Chespin", "Hypno", "Vikavolt", "Leafeon", "Hatterene"]),
    new Spawner(new Pos(684, 115, 1675), ["Blipbug", "Pachirisu", "Nickit", "Stantler", "Dedenne", "Poochyena", "Greedent", "Teddiursa", "Dottler", "Exeggcute", "Heracross", "Pinsir", "Applin", "Pikachu", "Thievul", "Klefki", "Mightyena", "Snorlax", "Orbeetle", "Ursaring"]),
    new Spawner(new Pos(660, 40, 1630), ["Spinarak", "Timburr", "Hoothoot", "Drilbur", "Haunter", "Ariados", "Klefki", "Excadrill", "Noctowl", "Chimecho", "Noibat", "Gengar", "Noivern", "Stonjourner", "Amoonguss"], true),
    new Spawner(new Pos(674, 40, 1588), ["Bunnelby", "Spinarak", "Gastly", "Rockruff", "Woobat", "Drilbur", "Noctowl", "Ariados", "Excadrill", "Haunter", "Chimecho", "Carbink", "Stonjourner", "Gengar", "Amoonguss"], true),
    new Spawner(new Pos(635, 40, 1588), ["Spinarak", "Timburr", "Hoothoot", "Drilbur", "Haunter", "Ariados", "Klefki", "Excadrill", "Noctowl", "Chimecho", "Noibat", "Gengar", "Noivern", "Stonjourner", "Amoonguss"], true),
    new Spawner(new Pos(750, 74, 1573), ["Bunnelby", "Spinarak", "Gastly", "Rockruff", "Woobat", "Drilbur", "Noctowl", "Ariados", "Excadrill", "Haunter", "Chimecho", "Carbink", "Stonjourner", "Gengar", "Amoonguss"])
]);

const W_MEGATAIGA = new Biome("Mega Taiga", ["megataiga"], new Pos(9, 80, 7335), new Pos(194, 0, 155), [
    new Spawner(new Pos(-21, 75, 7354), ["Pineco", "Yungoos", "Nincada", "Grubbin", "Rockruff", "Seedot", "Spearow", "Rowlet", "Ninjask", "Nuzleaf", "Gumshoos", "Forretress", "Dartrix", "Shiftry", "Fearow", "Shedinja", "Decidueye"]),
    new Spawner(new Pos(-41, 74, 7310), ["Skwovet", "Poochyena", "Rookidee", "Tarountula", "Stantler", "Dustox", "Exeggcute", "Heracross", "Sudowoodo", "Seedot", "Teddiursa", "Dedenne", "Gligar", "Ursaring", "Spidops", "Rowlet", "Snorlax", "Dartrix"]),
    new Spawner(new Pos(-107, 74, 7294), ["Pidgey", "Teddiursa", "Abra", "Ursaring", "Pidgeotto", "Togetic", "Togedemaru", "Kadabra", "Pikachu", "Sudowoodo", "Seedot", "Raichu", "Pidgeot", "Snorlax", "Yungoos"]),
    new Spawner(new Pos(-96, 79, 7348), ["Ferroseed", "Bunnelby", "Timburr", "Deerling", "Gligar", "Munna", "Elgyem", "Morpeko", "Gurdurr", "Pikachu", "Diggersby", "Musharna", "Sawsbuck", "Beheeyem", "Ferrothorn", "Conkeldurr", "Gliscor"]),
    new Spawner(new Pos(-60, 74, 7392), ["Kricketot", "Wurmple", "Blipbug", "Stantler", "Dustox", "Pachirisu", "Exeggcute", "Heracross", "Sudowoodo", "Seedot", "Teddiursa", "Gligar", "Dedenne", "Kricketune", "Ursaring", "Snorlax", "Decidueye"]),
    new Spawner(new Pos(-21, 75, 7354), ["Pineco", "Yungoos", "Nincada", "Grubbin", "Rockruff", "Seedot", "Spearow", "Rowlet", "Ninjask", "Nuzleaf", "Gumshoos", "Forretress", "Dartrix", "Shiftry", "Fearow", "Shedinja", "Decidueye"]),
    new Spawner(new Pos(9, 75, 7378), ["Vulpix", "Toedscool", "Tinkatink", "Tandemaus", "Hoothoot", "Weedle", "Kricketot", "Kakuna", "Maushold", "Tinkatuff", "Toedscruel", "Kricketune", "Noctowl", "Beedrill", "Ninetales", "Tinkaton", "Snorlax", "Vikavolt"]),
    new Spawner(new Pos(30, 78, 7420), ["Hoothoot", "Spinarak", "Seedot", "Gastly", "Pineco", "Murkrow", "Nuzleaf", "Dustox", "Forretress", "Kadabra", "Noctowl", "Haunter", "Pikachu", "Ariados", "MimeJr", "MrMime", "Snorlax", "Sudowoodo", "Teddiursa", "Raichu", "Ursaring"]),
    new Spawner(new Pos(-17, 73, 7199), ["Hoothoot", "Spinarak", "Seedot", "Gastly", "Pineco", "Murkrow", "Nuzleaf", "Dustox", "Forretress", "Kadabra", "Noctowl", "Haunter", "Pikachu", "Ariados", "MimeJr", "MrMime", "Snorlax", "Sudowoodo", "Teddiursa", "Raichu", "Ursaring"]),
    new Spawner(new Pos(22, 74, 7262), ["Pidgey", "Teddiursa", "Abra", "Ursaring", "Pidgeotto", "Togetic", "Togedemaru", "Kadabra", "Pikachu", "Sudowoodo", "Seedot", "Raichu", "Pidgeot", "Snorlax", "Yungoos"]),
    new Spawner(new Pos(66, 74, 7344), ["Skwovet", "Rockruff", "Rookidee", "Grubbin", "Deerling", "Milcery", "Heracross", "Sudowoodo", "Seedot", "Teddiursa", "Dedenne", "Chespin", "Volbeat", "Illumise", "Sawsbuck", "Leafeon"]),
    new Spawner(new Pos(56, 86, 7336), ["Kricketot", "Wurmple", "Blipbug", "Stantler", "Dustox", "Pachirisu", "Exeggcute", "Heracross", "Sudowoodo", "Seedot", "Teddiursa", "Gligar", "Dedenne", "Kricketune", "Ursaring", "Snorlax", "Decidueye"]),
    new Spawner(new Pos(34, 97, 7383), ["Skwovet", "Poochyena", "Rookidee", "Tarountula", "Stantler", "Dustox", "Exeggcute", "Heracross", "Sudowoodo", "Seedot", "Teddiursa", "Ursaring", "Spidops", "Rowlet", "Snorlax", "Dartrix"]),
    new Spawner(new Pos(-50, 98, 7417), ["Skwovet", "Rockruff", "Rookidee", "Grubbin", "Deerling", "Milcery", "Heracross", "Sudowoodo", "Seedot", "Teddiursa", "Dedenne", "Chespin", "Volbeat", "Illumise", "Sawsbuck", "Leafeon"]),
    new Spawner(new Pos(-65, 108, 7348), ["Rookidee", "Togedemaru", "Murkrow", "Grubbin", "Deerling", "Milcery", "Blipbug", "Vulpix", "Togedemaru", "Dottler", "Dedenne", "Chespin", "Charjabug", "Vikavolt", "MimeJr", "Leafeon"]) // duplicate: Togedemaru
]);

const W_COLDTAIGA = new Biome("Cold Taiga", ["coldtaiga"], new Pos(2830, 77, -6859), new Pos(142, 0, 144), [
    new Spawner(new Pos(2800, 75, -6846), ["Buneary", "Snom", "Skwovet", "Stantler", "Pachirisu", "Togedemaru", "Sneasel", "Jynx", "Wobbuffet", "Sandslash (Alolan)", "Vulpix (Alolan)", "Darumaka (Galarian)", "Meowth (Galarian)", "MrRime", "Frosmoth"]),
    new Spawner(new Pos(2785, 75, -6854), ["Pineco", "Sneasel", "Delibird", "Seel", "Wobbuffet", "Forretress", "Dewgong", "Jynx", "Magnemite", "Piplup", "Prinplup", "Empoleon", "Magneton", "Sneasel (Hisuian)"]),
    new Spawner(new Pos(2741, 74, -6827), ["Cubchoo", "Vanillite", "Buneary", "Deerling", "Karrablast", "Vulpix", "Sneasel (Hisuian)", "Vanillish", "Sawsbuck", "Vulpix (Alolan)", "Beartic", "Vanilluxe", "Ninetales (Alolan)", "Lopunny", "Frosmoth", "Sneasler"]),
    new Spawner(new Pos(2711, 74, -6839), ["Buneary", "Snom", "Skwovet", "Stantler", "Pachirisu", "Togedemaru", "Sneasel", "Jynx", "Wobbuffet", "Sandslash (Alolan)", "Vulpix (Alolan)", "Darumaka (Galarian)", "Meowth (Galarian)", "MrRime", "Frosmoth"]),
    new Spawner(new Pos(2711, 75, -6877), ["Shellder", "Magikarp", "Seel", "Spheal", "Sealeo", "Dewgong", "Cloyster"]),
    new Spawner(new Pos(2797, 77, -6977), ["Snom", "Sneasel", "Snover", "Spheal", "Magnemite", "Meowth", "Sealeo", "Perrserker", "Magneton", "Abomasnow", "Greedent", "Piplup", "Vulpix (Alolan)", "Walrein", "Prinplup", "Empoleon"]),
    new Spawner(new Pos(2821, 77, -6923), ["Cubchoo", "Vanillite", "Buneary", "Deerling", "Karrablast", "Vulpix", "Sneasel (Hisuian)", "Vanillish", "Sawsbuck", "Vulpix (Alolan)", "Beartic", "Vanilluxe", "Ninetales (Alolan)", "Lopunny", "Frosmoth", "Sneasler"]),
    new Spawner(new Pos(2846, 78, -6988), ["Snover", "Bergmite", "Buneary", "Spheal", "Magnemite", "Pachirisu", "Fletchling", "Sealeo", "Glalie", "Magneton", "Abomasnow", "Froslass", "Vulpix (Alolan)", "Walrein", "Darumaka (Galarian)", "Frosmoth", "Wyrdeer"]),
    new Spawner(new Pos(2854, 77, -6874), ["Shellder", "Magikarp", "Seel", "Spheal", "Sealeo", "Dewgong", "Cloyster"]),
    new Spawner(new Pos(2917, 77, -6853), ["Seel", "Cubchoo", "Deerling", "Magnemite", "Snorunt", "Dewgong", "Castform", "Sawsbuck", "Glalie", "Beartic", "Wobbuffet", "Piplup", "Prinplup", "Empoleon"]),
    new Spawner(new Pos(2946, 77, -6864), ["Pineco", "Sneasel", "Delibird", "Seel", "Wobbuffet", "Forretress", "Dewgong", "Jynx", "Magnemite", "Piplup", "Prinplup", "Empoleon", "Magneton", "Sneasel (Hisuian)"]),
    new Spawner(new Pos(2943, 76, -6809), ["Snover", "Bergmite", "Buneary", "Spheal", "Magnemite", "Pachirisu", "Fletchling", "Sealeo", "Glalie", "Magneton", "Abomasnow", "Froslass", "Vulpix (Alolan)", "Walrein", "Darumaka (Galarian)", "Frosmoth", "Wyrdeer"]),
    new Spawner(new Pos(2914, 75, -6762), ["Seel", "Delibird", "Magnemite", "Wobbuffet", "Forretress", "Cryogonal", "Ferroseed", "Dewgong", "Jynx", "Magneton", "Piplup", "Ferrothorn", "Prinplup", "Vulpix (Alolan)", "Empoleon"]),
    new Spawner(new Pos(2826, 76, -6835), ["Snom", "Sneasel", "Snover", "Spheal", "Magnemite", "Meowth", "Sealeo", "Perrserker", "Magneton", "Abomasnow", "Greedent", "Piplup", "Vulpix (Alolan)", "Walrein", "Prinplup", "Empoleon"]),
    new Spawner(new Pos(2740, 75, -6780), ["Seel", "Cubchoo", "Deerling", "Magnemite", "Snorunt", "Dewgong", "Castform", "Sawsbuck", "Glalie", "Beartic", "Wobbuffet", "Piplup", "Prinplup", "Empoleon"]),
    new Spawner(new Pos(2725, 90, -6892), ["Seel", "Delibird", "Magnemite", "Wobbuffet", "Forretress", "Cryogonal", "Ferroseed", "Dewgong", "Jynx", "Magneton", "Piplup", "Ferrothorn", "Prinplup", "Vulpix (Alolan)", "Empoleon"]),
    new Spawner(new Pos(2826, 95, -6790), ["Spheal", "Ferroseed", "Buneary", "Fletchling", "Stantler", "Deerling", "Pachirisu", "Jynx", "Wobbuffet", "MrMime", "Shellder", "Eiscue", "Darumaka (Galarian)", "Sandshrew (Alolan)", "Weavile", "Wynaut", "MrRime"]),
    new Spawner(new Pos(2826, 41, -6869), ["Spheal", "Ferroseed", "Buneary", "Fletchling", "Stantler", "Deerling", "Pachirisu", "Jynx", "Wobbuffet", "MrMime", "Shellder", "Eiscue", "Darumaka (Galarian)", "Sandshrew (Alolan)", "Weavile", "Wynaut", "MrRime"], true),
    new Spawner(new Pos(2837, 41, -6851), ["Bergmite", "Klink", "Spheal", "Sneasel", "Bronzor", "Magnemite", "Meowth (Galarian)", "Drilbur", "Jynx", "Eiscue", "Ferrothorn", "Glalie", "Perrserker", "Weavile", "Cryogonal"], true),
    new Spawner(new Pos(2853, 41, -6870), ["Vanillite", "Ferroseed", "Spheal", "Sneasel", "Seel", "Magnemite", "Meowth (Alolan)", "Sandslash (Alolan)", "Jynx", "Eiscue", "Ferrothorn", "Glalie", "Perrserker", "Weavile", "Cryogonal", "Walrein", "Spheal"], true)
]);

const W_ICESPIKES = new Biome("Ice Spikes", ["icespikes"], new Pos(3464, 78, -6334), new Pos(175, 0, 139), [
    new Spawner(new Pos(3380, 74, -6350), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Spheal", "Sealeo", "Bergmite", "Snom", "Zorua (Hisuian)", "Piplup", "Beartic", "Zoroark (Hisuian)", "Walrein", "Metagross", "Avalugg (Hisuian)"]),
    new Spawner(new Pos(3320, 73, -6384), ["Delibird", "Seel", "Piloswine", "Snorunt", "Dewgong", "Swinub", "Magnemite", "Glalie", "Piplup", "Prinplup", "Empoleon", "Magneton", "Avalugg"]),
    new Spawner(new Pos(3386, 74, -6441), ["Delibird", "Seel", "Piloswine", "Snorunt", "Dewgong", "Swinub", "Magnemite", "Glalie", "Piplup", "Prinplup", "Empoleon", "Magneton", "Crabominable"]),
    new Spawner(new Pos(3509, 79, -6379), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Swinub", "Vanillish", "Bergmite", "Snom", "Piplup", "Empoleon", "Sandshrew (Alolan)", "Froslass"]),
    new Spawner(new Pos(3538, 76, -6343), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Swinub", "Magnemite", "Bergmite", "Snom", "Piplup", "Empoleon", "Crabominable", "Glaceon"]),
    new Spawner(new Pos(3476, 80, -6389), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Swinub", "Vanillish", "Spheal", "Sealeo", "Seel", "Bergmite", "Snom", "Castform", "Sandshrew (Alolan)", "Cryogonal", "Vanilluxe"]),
    new Spawner(new Pos(3451, 79, -6404), ["Seel", "Bergmite", "Greavard", "Cetoddle", "Frigibax", "Eiscue", "Dewgong", "Avalugg", "Cetitan", "Houndstone", "Arctibax", "Frosmoth", "Baxcalibur", "Cryogonal"]),
    new Spawner(new Pos(3442, 78, -6366), ["Delibird", "Seel", "Swinub", "Snorunt", "Dewgong", "Piloswine", "Magnemite", "Glalie", "Piplup", "Prinplup", "Empoleon", "Magneton", "Vanilluxe", "Avalugg"]),
    new Spawner(new Pos(3481, 77, -6301), ["Bergmite", "Magnemite", "Eiscue", "Magneton", "Piplup", "Beldum", "Avalugg", "Prinplup", "Frigibax", "Empoleon", "Metang", "Arctibax", "Baxcalibur", "Metagross", "Avalugg (Hisuian)", "Magnezone"]),
    new Spawner(new Pos(3521, 76, -6305), ["Seel", "Bergmite", "Greavard", "Cetoddle", "Frigibax", "Eiscue", "Dewgong", "Avalugg", "Cetitan", "Houndstone", "Arctibax", "Frosmoth", "Baxcalibur", "Cryogonal"]),
    new Spawner(new Pos(3523, 78, -6290), ["Delibird", "Seel", "Piloswine", "Snorunt", "Dewgong", "Swinub", "Magnemite", "Glalie", "Piplup", "Prinplup", "Empoleon", "Magneton", "Crabominable"]),
    new Spawner(new Pos(3479, 88, -6236), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Spheal", "Sealeo", "Bergmite", "Snom", "Zorua (Hisuian)", "Piplup", "Beartic", "Zoroark (Hisuian)", "Walrein", "Metagross", "Avalugg (Hisuian)"]),
    new Spawner(new Pos(3432, 79, -6300), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Swinub", "Vanillish", "Spheal", "Sealeo", "Seel", "Bergmite", "Snom", "Castform", "Sandshrew (Alolan)", "Cryogonal"]),
    new Spawner(new Pos(3435, 75, -6236), ["Snorunt", "Cubchoo", "Pidove", "Vanillite", "Swinub", "Vanillish", "Bergmite", "Snom", "Piplup", "Empoleon", "Sandshrew (Alolan)", "Froslass"]) // spelling mistake: Piplup -> Piplip
]);

const W_ICEPLAINS = new Biome("Ice Plains", ["iceplains"], new Pos(5753, 77, -2738), new Pos(172, 0, 164), [
    new Spawner(new Pos(5774, 75, -2791), ["Seel", "Mareep", "Cubchoo", "Snorunt", "Snom", "Swinub", "Magnemite", "Magneton", "Meowth (Alolan)", "Vulpix (Alolan)", "Beartic", "Mamoswine", "Glaceon"]),
    new Spawner(new Pos(5803, 76, -2751), ["Seel", "Swinub", "Vanillite", "Dewgong", "Snorunt", "Piloswine", "Vanillish", "Magnemite", "Glalie", "Piplup", "Prinplup", "Empoleon"]),
    new Spawner(new Pos(5849, 76, -2789), ["Seel", "Mareep", "Wooloo", "Snorunt", "Snom", "Flaaffy", "Magnemite", "Zigzagoon", "Eiscue", "Skiddo", "Dubwool", "Obstagoon"]),
    new Spawner(new Pos(5780, 77, -2864), ["Bergmite", "Vanillite", "Cubchoo", "Mareep", "Snom", "Swinub", "Magnemite", "Glalie", "Eiscue", "Vulpix (Alolan)", "Avalugg", "Mamoswine", "Dubwool"]),
    new Spawner(new Pos(5377, 76, -2805), ["Seel", "Mareep", "Cubchoo", "Snorunt", "Snom", "Swinub", "Magnemite", "Magneton", "Meowth (Alolan)", "Vulpix (Alolan)", "Beartic", "Mamoswine", "Glaceon"]),
    new Spawner(new Pos(5810, 73, -2682), ["Seel", "Mareep", "Wooloo", "Snorunt", "Snom", "Flaaffy", "Magnemite", "Zigzagoon", "Eiscue", "Skiddo", "Dubwool", "Obstagoon"]),
    new Spawner(new Pos(5730, 74, -2752), ["Seel", "Swinub", "Vanillite", "Dewgong", "Snorunt", "Piloswine", "Vanillish", "Magnemite", "Glalie", "Piplup", "Prinplup", "Empoleon"]),
    new Spawner(new Pos(5632, 73, -2695), ["Bergmite", "Snover", "Cubchoo", "Magnemite", "Swinub", "Klink", "Klinklang", "Magneton", "Abomasnow", "Eiscue", "Perrserker", "Mawile", "Minior", "Magnezone"]),
    new Spawner(new Pos(5740, 91, -2882), ["Bergmite", "Snover", "Cubchoo", "Magnemite", "Swinub", "Klink", "Klinklang", "Magneton", "Abomasnow", "Eiscue", "Perrserker", "Mawile", "Minior", "Magnezone"]),
    new Spawner(new Pos(5741, 91, -2880), ["Bergmite", "Vanillite", "Cubchoo", "Mareep", "Snom", "Swinub", "Magnemite", "Glalie", "Eiscue", "Vulpix (Alolan)", "Avalugg", "Mamoswine", "Dubwool"])
]);

const W_SWAMP = new Biome("Swamp", ["swamp"], new Pos(1743, 78, 4552), new Pos(143, 0, 143), [
    new Spawner(new Pos(1713, 77, 4541), ["Dewpider", "Barboach", "Poliwag", "Croagunk", "Whiscash", "Magikarp", "Toxel", "Goldeen", "Lotad", "Carvanha", "Feebas", "Surskit", "Wooper", "Basculin", "Araquanid", "Goomy", "Toxtricity", "Toxicroak", "Sliggoo", "Goodra"]),
    new Spawner(new Pos(1686, 74, 4565), ["Bidoof", "Lotad", "Wooper", "Tympole", "Ducklett", "Tadbulb", "Flamigo", "Lombre", "Palpitoad", "Bibarel", "Wooper (Paldean)", "Dondozo", "Quagsire", "Seismitoad", "Swanna", "Ludicolo", "Clodsire", "Bellibolt"]),
    new Spawner(new Pos(1657, 75, 4592), ["Wooper", "Lotad", "Shelmet", "Solosis", "Toxel", "Trubbish", "Lombre", "Poliwag", "Grimer", "Barboach", "Duosion", "Koffing", "Grimer (Alolan)", "Muk", "Garbodor", "Weezing", "Karrablast", "Whiscash", "Muk (Alolan)", "Weezing (Galarian)", "Feebas"], true),
    new Spawner(new Pos(1660, 74, 4510), ["Bidoof", "Corphish", "Ekans", "Chewtle", "Grimer", "Lotad", "Oddish", "Paras", "Shelmet", "Yanma", "Bibarel", "Arbok", "Lombre", "Dewpider", "Gulpin", "Stunfisk (Galarian)", "Drednaw", "Ludicolo", "Swalot", "Yanmega"], true),
    new Spawner(new Pos(1752, 75, 4515), ["Tympole", "Hypno", "Woobat", "Shelmet", "Stunky", "Skorupi", "Solosis", "Drifloon", "Croagunk", "Gothita", "Drapion", "Stunfisk", "Carnivine", "Duosion", "Toxicroak", "Palpitoad", "Drifblim", "Skuntank", "Tangrowth", "Goomy", "Swoobat", "Gothorita", "Sliggoo", "Mudkip", "Marshtomp", "Swampert", "Reuniclus"]),
    new Spawner(new Pos(1720, 76, 4469), ["Paras", "Murkrow", "Venonat", "Drifloon", "Skorupi", "Gligar", "Koffing", "Grimer", "Drowzee", "Gulpin", "Slowpoke", "Venomoth", "Drapion", "Weezing", "Slowbro", "Muk", "Drifblim", "Trubbish", "Woobat", "Garbodor", "Honchkrow"]),
    new Spawner(new Pos(1674, 74, 4453), ["Tympole", "Hypno", "Woobat", "Shelmet", "Stunky", "Skorupi", "Solosis", "Drifloon", "Croagunk", "Gothita", "Drapion", "Stunfisk", "Carnivine", "Duosion", "Toxicroak", "Palpitoad", "Drifblim", "Skuntank", "Tangrowth", "Goomy", "Swoobat", "Gothorita", "Sliggoo", "Mudkip", "Marshtomp", "Swampert", "Reuniclus"]),
    new Spawner(new Pos(1695, 90, 4623), ["Oddish", "Poliwag", "Psyduck", "Bellsprout", "Solosis", "Golduck", "Poliwhirl", "Duosion", "Slowpoke", "Wooper", "Weepinbell", "Tangela", "Quagsire", "Slowbro", "Masquerain", "Froakie", "Gligar", "Frogadier", "Greninja", "Reuniclus", "Mudkip", "Marshtomp", "Ursaluna"]),
    new Spawner(new Pos(1660, 106, 4592), ["Oddish", "Poliwag", "Psyduck", "Bellsprout", "Solosis", "Golduck", "Poliwhirl", "Duosion", "Wooper", "Tangela", "Toxel", "Quagsire", "Slowbro", "Toxtricity", "Froakie", "Gligar", "Frogadier", "Greninja", "Reuniclus", "Marshtomp", "Mudkip", "Stunfisk (Galarian)", "Swampert"]),
    new Spawner(new Pos(1788, 92, 4484), ["Oddish", "Poliwag", "Psyduck", "Bellsprout", "Solosis", "Golduck", "Poliwhirl", "Duosion", "Slowpoke", "Wooper", "Weepinbell", "Tangela", "Quagsire", "Slowbro", "Masquerain", "Froakie", "Gligar", "Frogadier", "Greninja", "Reuniclus", "Mudkip", "Marshtomp", "Ursaluna"]),
    new Spawner(new Pos(1853, 72, 4495), ["Wooper", "Lotad", "Shelmet", "Solosis", "Toxel", "Trubbish", "Lombre", "Poliwag", "Grimer", "Barboach", "Duosion", "Koffing", "Grimer (Alolan)", "Muk", "Garbodor", "Weezing", "Karrablast", "Whiscash", "Muk (Alolan)", "Weezing (Galarian)", "Feebas"]),
    new Spawner(new Pos(1801, 89, 4559), ["Paras", "Murkrow", "Venonat", "Drifloon", "Skorupi", "Gligar", "Koffing", "Grimer", "Drowzee", "Gulpin", "Slowpoke", "Venomoth", "Drapion", "Weezing", "Slowbro", "Muk", "Drifblim", "Trubbish", "Woobat", "Garbodor", "Honchkrow"]),
    new Spawner(new Pos(1787, 89, 4583), ["Dewpider", "Barboach", "Poliwag", "Croagunk", "Whiscash", "Magikarp", "Toxel", "Goldeen", "Lotad", "Carvanha", "Bellsprout", "Surskit", "Wooper", "Basculin", "Araquanid", "Goomy", "Toxtricity", "Toxicroak", "Sliggoo", "Goodra"]),
    new Spawner(new Pos(1810, 88, 4595), ["Bidoof", "Corphish", "Ekans", "Chewtle", "Grimer", "Lotad", "Oddish", "Paras", "Shelmet", "Yanma", "Bibarel", "Arbok", "Lombre", "Dewpider", "Gulpin", "Stunfisk (Galarian)", "Drednaw", "Ludicolo", "Swalot", "Yanmega"], true),
    new Spawner(new Pos(1764, 74, 4586), ["Oddish", "Poliwag", "Psyduck", "Bellsprout", "Solosis", "Golduck", "Poliwhirl", "Duosion", "Wooper", "Tangela", "Toxel", "Quagsire", "Slowbro", "Toxtricity", "Froakie", "Gligar", "Frogadier", "Greninja", "Reuniclus", "Marshtomp", "Mudkip", "Stunfisk (Galarian)", "Swampert"]),
    new Spawner(new Pos(1763, 71, 4676), ["Dewpider", "Barboach", "Poliwag", "Croagunk", "Whiscash", "Magikarp", "Toxel", "Goldeen", "Lotad", "Carvanha", "Feebas", "Surskit", "Wooper", "Basculin", "Araquanid", "Goomy", "Toxtricity", "Toxicroak", "Sliggoo", "Goodra"]),
    new Spawner(new Pos(1696, 56, 4616), ["Paras", "Murkrow", "Venonat", "Drifloon", "Skorupi", "Gligar", "Koffing", "Grimer", "Drowzee", "Gulpin", "Slowpoke", "Venomoth", "Drapion", "Weezing", "Slowbro", "Muk", "Drifblim", "Trubbish", "Woobat", "Garbodor"], true),
    new Spawner(new Pos(1736, 56, 4651), ["Paras", "Murkrow", "Venonat", "Drifloon", "Skorupi", "Gligar", "Koffing", "Grimer", "Drowzee", "Gulpin", "Slowpoke", "Venomoth", "Drapion", "Weezing", "Slowbro", "Muk", "Drifblim", "Trubbish", "Woobat", "Rotom", "Garbodor"], true),
    new Spawner(new Pos(1725, 56, 4651), ["Ekans", "Chewtle", "Skorupi", "Stunky", "Gulpin", "Karrablast", "Corphish", "Gligar", "Zubat", "Golbat", "Arbok", "Drapion", "Drapion", "Sliggoo (Hisuian)", "Crawdaunt", "Drednaw", "Gliscor", "Skuntank", "Crobat"], true),
    new Spawner(new Pos(1726, 56, 4571), ["Paras", "Murkrow", "Venonat", "Drifloon", "Skorupi", "Gligar", "Koffing", "Grimer", "Drowzee", "Gulpin", "Slowpoke", "Venomoth", "Drapion", "Weezing", "Slowbro", "Muk", "Drifblim", "Trubbish", "Woobat", "Rotom", "Garbodor"], true),
    new Spawner(new Pos(1735, 56, 4571), ["Ekans", "Poliwag", "Skorupi", "Stunky", "Gulpin", "Poliwhirl", "Corphish", "Gligar", "Zubat", "Golbat", "Arbok", "Drapion", "Drapion", "Grimer (Alolan)", "Crawdaunt", "Poliwrath", "Gliscor", "Skuntank", "Politoed"], true) // duplicate: Drapion
]);

const W_MUSHROOM = new Biome("Mushroom", ["mushroom", "mushroomisland"], new Pos(3445, 72, 6031), new Pos(117, 0, 43), [
    new Spawner(new Pos(3452, 68, 6070), ["Morelull", "Paras", "Shroomish", "Foongus", "Munna", "Toedscool", "Swirlix", "Spritzee", "Parasect", "Breloom", "Amoonguss", "Toedscruel", "Shiinotic"]),
    new Spawner(new Pos(3510, 70, 6113), ["Shroomish", "Foongus", "Morelull", "Breloom", "Parasect", "Amoonguss", "Shiinotic", "Paras"]),
    new Spawner(new Pos(3534, 72, 6088), ["Morelull", "Paras", "Zubat", "Gastly", "Woobat", "Aron", "Noibat", "Solrock", "Drampa"], true),
    new Spawner(new Pos(3545, 67, 6134), ["Morelull", "Paras", "Shroomish", "Foongus", "Munna", "Toedscool", "Swirlix", "Spritzee", "Parasect", "Breloom", "Amoonguss", "Toedscruel", "Shiinotic", "Aromatisse", "Slurpuff"]),
    new Spawner(new Pos(3463, 68, 6148), ["Morelull", "Paras", "Shroomish", "Foongus", "Parasect", "Breloom", "Amoonguss", "Shiinotic", "Drampa"]),
    new Spawner(new Pos(3515, 71, 6199), ["Morelull", "Paras", "Shroomish", "Foongus", "Parasect", "Breloom", "Amoonguss", "Munna", "Spritzee", "Swirlix", "Shiinotic", "Musharna"]),
    new Spawner(new Pos(3543, 76, 6212), ["Foongus", "Paras", "Zubat", "Geodude", "Woobat", "Aron", "Spritzee", "Swirlix", "Lunatone", "Clefable"], true),
    new Spawner(new Pos(3440, 67, 6233), ["Shroomish", "Foongus", "Morelull", "Breloom", "Parasect", "Amoonguss", "Shiinotic", "Paras"]),
    new Spawner(new Pos(3401, 70, 6144), ["Morelull", "Paras", "Shroomish", "Foongus", "Parasect", "Breloom", "Amoonguss", "Munna", "Spritzee", "Swirlix", "Shiinotic", "Musharna"]),
    new Spawner(new Pos(3412, 70, 6057), ["Morelull", "Paras", "Shroomish", "Foongus", "Parasect", "Breloom", "Amoonguss", "Munna", "Spritzee", "Swirlix", "Shiinotic", "Drampa"])
]);

const W_FLOWERFOREST = new Biome("Flower Forest", ["flowerforest"], new Pos(1054, 72, 4908), new Pos(139, 0, 147), [
    new Spawner(new Pos(1070, 71, 4918), ["Cutiefly", "Cherubi", "Stunky", "Timburr", "Petilil", "Deerling", "Gossifleur", "Karrablast", "Gurdurr", "Bounsweet", "Ribombee", "Sprigatito", "Steenee", "Floragato", "Cherrim", "Sawsbuck", "Tsareena", "Skuntank", "Eldegoss", "Conkeldurr", "Meowscarada"]),
    new Spawner(new Pos(1116, 69, 4896), ["Zubat", "Joltik", "Jigglypuff", "Venonat", "Ducklett", "Carbink", "Golbat", "Foongus", "Pikachu", "Galvantula", "Wigglytuff", "Swanna", "Venomoth", "Amoonguss", "Pichu", "Igglybuff", "Mawile", "Leafeon", "Raichu", "Sylveon"]),
    new Spawner(new Pos(1080, 70, 4885), ["Bounsweet", "Skwovet", "Cherubi", "Hoppip", "Swirlix", "Skitty", "Flabebe", "Oddish", "Burmy", "Floette", "Gloom", "Foongus", "Bulbasaur", "Wormadam", "Vileplume", "Ivysaur", "Delcatty", "Greedent", "Whimsicott", "Bellossom", "Venusaur", "Florges"]),
    new Spawner(new Pos(1116, 70, 4808), ["Stunky", "Timburr", "Petilil", "Deerling", "Karrablast", "Gossifleur", "Cherrim", "Skuntank", "Sawsbuck", "Combee", "Roselia", "Beautifly", "Turtwig", "Pidgeotto", "Togetic", "Weepinbell", "Beedrill", "Butterfree", "Kadabra", "Kricketune", "Swadloon", "Sunflora", "Vespiquen"]),
    new Spawner(new Pos(1032, 70, 4796), ["Zubat", "Joltik", "Jigglypuff", "Venonat", "Ducklett", "Carbink", "Golbat", "Foongus", "Pikachu", "Galvantula", "Wigglytuff", "Swanna", "Venomoth", "Amoonguss", "Pichu", "Igglybuff", "Mawile", "Leafeon", "Raichu", "Sylveon"]),
    new Spawner(new Pos(1045, 75, 4837), ["Spinarak", "Ledyba", "Cascoon", "Silcoon", "Ledian", "Dustox", "Illumise", "Volbeat", "Jigglypuff", "Kadabra", "Kricketot", "Pinsir", "Ariados", "Joltik", "Applin", "Wigglytuff"]),
    new Spawner(new Pos(1064, 89, 4800), ["Caterpie", "Weedle", "Ledyba", "Oddish", "Cutiefly", "Gloom", "Kricketot", "Bounsweet", "Kakuna", "Metapod", "Heracross", "Ledian", "Beedrill", "Butterfree", "Jigglypuff", "Kricketune", "Joltik", "Scyther", "Steenee", "Comfey", "Galvantula", "Tsareena"]),
    new Spawner(new Pos(1074, 130, 4842), ["Bellsprout", "Spritzee", "Scatterbug", "Nickit", "Flabebe", "Sunkern", "Petilil", "Roselia", "Spewpa", "Floette", "Ledyba", "Ledian", "Chikorita", "Applin", "Budew", "Thievul", "Sunflora", "Bayleef", "Vivillon", "Roserade", "Lilligant", "Meganium"]),
    new Spawner(new Pos(1061, 139, 4821), ["Caterpie", "Weedle", "Ledyba", "Oddish", "Cutiefly", "Gloom", "Kricketot", "Bounsweet", "Kakuna", "Metapod", "Heracross", "Ledian", "Beedrill", "Butterfree", "Jigglypuff", "Kricketune", "Joltik", "Scyther", "Steenee", "Comfey", "Galvantula", "Tsareena"]),
    new Spawner(new Pos(1059, 69, 4947), ["Oddish", "Pidgey", "Wurmple", "Sewaddle", "Budew", "Cottonee", "Sunkern", "Bellsprout", "Silcoon", "Abra", "Scyther", "Applin", "Bulbasaur", "Chikorita", "Snivy", "Bayleef", "Ivysaur", "Servine", "Pidgeot", "Venusaur", "Meganium", "Serperior"]),
    new Spawner(new Pos(1082, 69, 4962), ["Bellsprout", "Spritzee", "Scatterbug", "Nickit", "Flabebe", "Sunkern", "Petilil", "Roselia", "Spewpa", "Floette", "Ledyba", "Ledian", "Chikorita", "Applin", "Budew", "Thievul", "Sunflora", "Bayleef", "Vivillon", "Roserade", "Lilligant", "Meganium"]),
    new Spawner(new Pos(1141, 72, 4937), ["Sewaddle", "Wurmple", "Nincada", "Combee", "Burmy", "Gossifleur", "Cascoon", "Silcoon", "Ninjask", "Ledyba", "Dustox", "Beautifly", "Illumise", "Volbeat", "Swadloon", "Pinsir", "Vespiquen", "Ribombee", "Leavanny", "Eldegoss"]),
    new Spawner(new Pos(1090, 69, 5020), ["Caterpie", "Weedle", "Ledyba", "Oddish", "Cutiefly", "Gloom", "Kricketot", "Bounsweet", "Kakuna", "Metapod", "Heracross", "Ledian", "Beedrill", "Butterfree", "Jigglypuff", "Kricketune", "Joltik", "Scyther", "Steenee", "Comfey", "Galvantula", "Tsareena"]),
    new Spawner(new Pos(1106, 98, 5000), ["Bounsweet", "Skwovet", "Cherubi", "Hoppip", "Swirlix", "Skitty", "Flabebe", "Oddish", "Burmy", "Floette", "Gloom", "Foongus", "Bulbasaur", "Wormadam", "Vileplume", "Ivysaur", "Delcatty", "Greedent", "Whimsicott", "Bellossom", "Venusaur", "Florges"]),
    new Spawner(new Pos(1097, 153, 4946), ["Cutiefly", "Flabebe", "Skitty", "Spritzee", "Swirlix", "Hoppip", "Applin", "Ducklett", "Pikachu", "Jumpluff", "Delcatty", "Swanna", "Cleffa", "Pichu", "Igglybuff", "Togepi", "Flapple", "Appletun", "Sylveon", "Florges"]),
    new Spawner(new Pos(1066, 152, 4935), ["Oddish", "Pidgey", "Wurmple", "Sewaddle", "Budew", "Cottonee", "Sunkern", "Bellsprout", "Silcoon", "Abra", "Scyther", "Applin", "Bulbasaur", "Chikorita", "Snivy", "Ponyta (Galarian)", "Bayleef", "Ivysaur", "Servine", "Pidgeot", "Venusaur", "Meganium", "Serperior", "Rapidash (Galarian)"]),
    new Spawner(new Pos(1083, 152, 4918), ["Bounsweet", "Skwovet", "Cherubi", "Hoppip", "Swirlix", "Skitty", "Flabebe", "Oddish", "Burmy", "Floette", "Gloom", "Foongus", "Bulbasaur", "Wormadam", "Vileplume", "Ivysaur", "Delcatty", "Greedent", "Whimsicott", "Bellossom", "Venusaur", "Florges"]),
    new Spawner(new Pos(1039, 68, 4980), ["Sewaddle", "Wurmple", "Nincada", "Combee", "Burmy", "Gossifleur", "Cascoon", "Silcoon", "Ninjask", "Ledyba", "Dustox", "Beautifly", "Illumise", "Volbeat", "Swadloon", "Pinsir", "Vespiquen", "Ribombee", "Leavanny", "Eldegoss"]),
    new Spawner(new Pos(1032, 70, 4892), ["Stunky", "Timburr", "Petilil", "Deerling", "Karrablast", "Gossifleur", "Cherrim", "Skuntank", "Sawsbuck", "Combee", "Roselia", "Beautifly", "Turtwig", "Pidgeotto", "Togetic", "Weepinbell", "Beedrill", "Butterfree", "Kadabra", "Kricketune", "Swadloon", "Sunflora", "Vespiquen"]),
    new Spawner(new Pos(982, 71, 4957), ["Cutiefly", "Cherubi", "Stunky", "Timburr", "Petilil", "Deerling", "Gossifleur", "Karrablast", "Gurdurr", "Bounsweet", "Ribombee", "Sprigatito", "Steenee", "Floragato", "Cherrim", "Sawsbuck", "Tsareena", "Skuntank", "Eldegoss", "Conkeldurr", "Meowscarada"]),
    new Spawner(new Pos(928, 67, 4925), ["Oddish", "Pidgey", "Wurmple", "Sewaddle", "Budew", "Cottonee", "Sunkern", "Bellsprout", "Silcoon", "Abra", "Scyther", "Applin", "Bulbasaur", "Chikorita", "Snivy", "Bayleef", "Ivysaur", "Servine", "Pidgeot", "Venusaur", "Meganium", "Serperior"]),
    new Spawner(new Pos(952, 71, 4902), ["Bellsprout", "Spritzee", "Scatterbug", "Nickit", "Flabebe", "Sunkern", "Petilil", "Roselia", "Spewpa", "Floette", "Ledyba", "Ledian", "Chikorita", "Applin", "Budew", "Thievul", "Sunflora", "Bayleef", "Vivillon", "Roserade", "Lilligant", "Meganium"])
]);

const W_MESA = new Biome("Mesa", ["mesa", "badlands"], new Pos(-241, 66, -5049), new Pos(141, 0, 195), [
    new Spawner(new Pos(-253, 64, -5026), ["Slugma", "Cubone", "Cacnea", "Scraggy", "Houndour", "Larvitar", "Aron", "Lunatone", "Boldore", "Graveler", "Lairon", "Dugtrio", "Bagon", "Smeargle", "Diglett (Alolan)", "Nosepass", "Golurk", "Aggron", "Runerigus", "Gigalith"]),
    new Spawner(new Pos(-289, 64, -5015), ["Rufflet", "Diglett", "Shuckle", "Dugtrio", "Rhyhorn", "Aron", "Nosepass", "Solrock", "Smeargle", "Druddigon", "Yamask", "Bronzor", "Rhydon", "Beldum", "Lairon", "Onix", "Spiritomb", "Cofagrigus", "Aggron", "Salamence", "Metang", "Metagross", "Carbink"]),
    new Spawner(new Pos(-323, 59, -5042), ["Natu", "Spearow", "Aron", "Vullaby", "Baltoy", "Rolycoly", "Golett", "Charmander", "Sigilyph", "Solrock", "Lunatone", "Fearow", "Charmeleon", "Xatu", "Golurk", "Claydol", "Mandibuzz", "Flareon", "Charizard"]),
    new Spawner(new Pos(-256, 64, -5100), ["Roggenrola", "Shuckle", "Diglett", "Geodude", "Golett", "Salandit", "Aron", "Larvitar", "Solrock", "Boldore", "Graveler", "Lairon", "Dugtrio", "Pupitar", "Unown", "Mandibuzz", "Nosepass", "Golurk", "Aggron", "Salazzle"]),
    new Spawner(new Pos(-241, 64, -5145), ["Charcadet", "Nacli", "Varoom", "Drilbur", "Baltoy", "Naclstack", "Golett", "Revavroom", "Fearow", "Cyndaquil", "Fuecoco", "Charmander", "Crocalor", "Garganacl", "Golurk", "Claydol", "Ceruledge", "Armarouge", "Skeledirge"]),
    new Spawner(new Pos(-202, 64, -5122), ["Diglett", "Torkoal", "Silicobra", "Aron", "Durant", "Sizzlipede", "Bramblin", "Skorupi", "Vullaby", "Onix", "Beldum", "Heatmor", "Dugtrio", "Nosepass", "Solrock", "Yamask (Galarian)", "Sandaconda", "Charmander", "Aggron", "Coalossal", "Brambleghast"]),
    new Spawner(new Pos(-153, 64, -5113), ["Cubone", "Sandshrew", "Skorupi", "Bunnelby", "Houndour", "Rhyhorn", "Numel", "Rhydon", "Marowak", "Drapion", "Cyndaquil", "Houndoom", "Marowak (Alolan)", "Quilava", "Mandibuzz", "Camerupt", "Typhlosion", "Rhyperior"]),
    new Spawner(new Pos(-214, 64, -5168), ["Roggenrola", "Rolycoly", "Shuckle", "Diglett", "Geodude", "Golett", "Larvitar", "Solrock", "Boldore", "Graveler", "Lairon", "Dugtrio", "Pupitar", "Unown", "Aron", "Nosepass", "Golurk", "Probopass", "Aggron"]),
    new Spawner(new Pos(181, 64, -5159), ["Diglett", "Geodude", "Slugma", "Sandshrew", "Roggenrola", "Shuckle", "Golett", "Houndour", "Larvitar", "Skorupi", "Boldore", "Graveler", "Sandslash", "Dugtrio", "Magcargo","Pupitar", "Baltoy", "Claydol", "Drapion", "Houndoom", "Unown", "Bagon", "Marowak", "Metang", "Onix", "Shelgon", "Aron", "Nosepass", "Golurk", "Tyranitar", "Beldum", "Lairon", "Aggron", "Metagross", "Salamence"]),
    new Spawner(new Pos(-134, 65, -5142), ["Slugma", "Cubone", "Cacnea", "Scraggy", "Houndour", "Larvitar", "Aron", "Lunatone", "Boldore", "Graveler", "Lairon", "Dugtrio", "Bagon", "Smeargle", "Diglett (Alolan)", "Nosepass", "Golurk", "Aggron", "Runerigus", "Gigalith"], true),
    new Spawner(new Pos(-229, 66, -5011), ["Drilbur", "Klink", "Onix", "Geodude", "Cacnea", "Maractus", "Klang", "Graveler", "Durant", "Bagon", "Noibat", "Cacturne", "Dunsparce", "Klinklang", "Excadrill", "Golem", "Steelix", "Noivern", "Kleavor"], true),
    new Spawner(new Pos(-142, 76, -5171), ["Bronzor", "Scraggy", "Aron", "Slugma", "Klink", "Lairon", "Heatmor", "Sigilyph", "Klang", "Pupitar", "Beldum", "Scrafty", "Sableye", "Metang", "Klinklang", "Bronzong", "Aggron", "Tyranitar", "Metagross"]),
    new Spawner(new Pos(-145, 77, -5157), ["Cubone", "Sandshrew", "Skorupi", "Bunnelby", "Houndour", "Rhyhorn", "Numel", "Rhydon", "Marowak", "Drapion", "Cyndaquil", "Houndoom", "Marowak (Alolan)", "Quilava", "Mandibuzz", "Camerupt", "Typhlosion", "Rhyperior"]),
    new Spawner(new Pos(-158, 79, -5153), ["Diglett", "Torkoal", "Silicobra", "Aron", "Durant", "Sizzlipede", "Skorupi", "Vullaby", "Onix", "Beldum", "Heatmor", "Dugtrio", "Nosepass", "Solrock", "Yamask (Galarian)", "Sandaconda", "Charmander", "Aggron", "Coalossal", "Centiskorch"]),
    new Spawner(new Pos(-201, 111, -5069), ["Rufflet", "Diglett", "Shuckle", "Dugtrio", "Rhyhorn", "Aron", "Nosepass", "Solrock", "Smeargle", "Druddigon", "Yamask", "Bronzor", "Rhydon", "Beldum", "Lairon", "Onix", "Spiritomb", "Cofagrigus", "Aggron", "Salamence", "Metang", "Metagross", "Carbink"]),
    new Spawner(new Pos(-186, 108, -5077), ["Drilbur", "Klink", "Capsakid", "Onix", "Cacnea", "Maractus", "Klang", "Scovillain", "Durant", "Bagon", "Noibat", "Kleavor", "Cacturne", "Dunsparce", "Klinklang", "Excadrill", "Golem", "Steelix", "Noivern"]),
    new Spawner(new Pos(-202, 108, -5083), ["Bronzor", "Scraggy", "Aron", "Slugma", "Klink", "Lairon", "Heatmor", "Sigilyph", "Klang", "Pupitar", "Beldum", "Scrafty", "Sableye", "Metang", "Klinklang", "Bronzong", "Aggron", "Tyranitar", "Metagross", "Iron Moth"]),
    new Spawner(new Pos(-249, 73, -4997), ["Cubone", "Sandshrew", "Skorupi", "Bunnelby", "Houndour", "Rhyhorn", "Numel", "Rhydon", "Marowak", "Drapion", "Cyndaquil", "Houndoom", "Marowak (Alolan)", "Quilava", "Mandibuzz", "Camerupt", "Typhlosion", "Rhyperior"]),
    new Spawner(new Pos(-162, 65, -5020), ["Rolycoly", "Sizzlipede", "Vullaby", "Carbink", "Carkol", "Nosepass", "Bagon", "Tynamo", "Charmander", "Eelektrik", "Geodude (Alolan)", "Graveler (Alolan)", "Smeargle", "Mandibuzz", "Eelektross", "Coalossal", "Centiskorch", "Probopass", "Golem (Alolan)"]),
    new Spawner(new Pos(-126, 72, -5135), ["Rufflet", "Diglett", "Shuckle", "Dugtrio", "Rhyhorn", "Aron", "Nosepass", "Solrock", "Smeargle", "Druddigon", "Yamask", "Bronzor", "Rhydon", "Beldum", "Lairon", "Onix", "Spiritomb", "Cofagrigus", "Aggron", "Salamence", "Metang", "Metagross", "Carbink"], true),
    new Spawner(new Pos(-182, 80, -5104), ["Roggenrola", "Shuckle", "Diglett", "Geodude", "Golett", "Salandit", "Aron", "Larvitar", "Solrock", "Boldore", "Graveler", "Lairon", "Dugtrio", "Pupitar", "Unown", "Mandibuzz", "Nosepass", "Golurk", "Aggron", "Salazzle"]),
    new Spawner(new Pos(-161, 81, -5060), ["Diglett", "Torkoal", "Silicobra", "Aron", "Durant", "Sizzlipede", "Bramblin", "Skorupi", "Vullaby", "Onix", "Beldum", "Heatmor", "Dugtrio", "Nosepass", "Solrock", "Yamask (Galarian)", "Sandaconda", "Charmander", "Aggron", "Coalossal", "Brambleghast"], true),
    new Spawner(new Pos(-169, 89, -5177), ["Roggenrola", "Rolycoly", "Shuckle", "Diglett", "Geodude", "Golett", "Larvitar", "Solrock", "Boldore", "Graveler", "Lairon", "Dugtrio", "Pupitar", "Unown", "Aron", "Nosepass", "Golurk", "Probopass", "Aggron"], true),
    new Spawner(new Pos(-137, 98, -5122), ["Rolycoly", "Sizzlipede", "Golett", "Vullaby", "Baltoy", "Torkoal", "Nosepass", "Bagon", "Cleffa", "Charmander", "Clefairy", "Carbink", "Claydol", "Smeargle", "Mandibuzz", "Clefable", "Coalossal", "Centiskorch", "Probopass", "Golurk"], true),
    new Spawner(new Pos(-281, 89, -5204), ["Diglett", "Geodude", "Slugma", "Sandshrew", "Roggenrola", "Shuckle", "Golett", "Houndour", "Larvitar", "Skorupi", "Boldore", "Graveler", "Sandslash", "Dugtrio", "Magcargo","Pupitar", "Baltoy", "Claydol", "Drapion", "Houndoom", "Unown", "Bagon", "Marowak", "Metang", "Onix", "Shelgon", "Aron", "Nosepass", "Golurk", "Tyranitar", "Beldum", "Lairon", "Aggron", "Metagross", "Salamence"], true),
    new Spawner(new Pos(-289, 47, -5113), ["Nacli", "Spearow", "Aron", "Vullaby", "Baltoy", "Naclstack", "Golett", "Fuecoco", "Sigilyph", "Larvitar", "Beldum", "Fearow", "Crocalor", "Garganacl", "Golurk", "Claydol", "Mandibuzz", "Tyranitar", "Skeledirge"]),
    new Spawner(new Pos(-305, 47, -5164), ["Natu", "Spearow", "Aron", "Vullaby", "Baltoy", "Rolycoly", "Golett", "Charmander", "Sigilyph", "Solrock", "Lunatone", "Fearow", "Charmeleon", "Xatu", "Golurk", "Claydol", "Mandibuzz", "Flareon", "Charizard"]),
    new Spawner(new Pos(-349, 47, -5113), ["Drilbur", "Klink", "Onix", "Geodude", "Cacnea", "Maractus", "Klang", "Graveler", "Durant", "Bagon", "Noibat", "Cacturne", "Dunsparce", "Klinklang", "Excadrill", "Golem", "Steelix", "Noivern", "Kleavor"])
]);

export const BIOMES = [
    W_PLAINS, W_BIRCHFOREST, W_DARKFOREST, W_OCEAN,
    W_JUNGLE, W_DESERT, W_EXTREMEHILLS, W_BEACH,
    W_SAVANNA, W_TAIGA, W_MEGATAIGA, W_COLDTAIGA,
    W_ICESPIKES, W_ICEPLAINS, W_SWAMP, W_MUSHROOM,
    W_FLOWERFOREST, W_MESA
];